generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SignosVitalesNursery
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          signos_vitales_nursery
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  
        fc_nursery:  {label: FC}
        fr_nursery:  {label: FR}
        to_nursery:  {label: To}
        diu_nursery: {label: DIU}
        cat_nursery: {label: CAT}
        lm_nursery:  {label: LM}
      list:    
        title: Signos Vitales Nursery
        display: [hora, fc_nursery, fr_nursery, to_nursery]
        actions: {}
        batch_actions: {}
      filter:  
        display: [hora, fc_nursery, fr_nursery, to_nursery]
      form:    ~
      edit:    
        title: Editar Signos Vitales Nursery
        actions:
          _save: ~
      new:     
        title: Nuevo Signos Vitales Nursery
        actions:
          _save: ~
          _save_and_add: ~