generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolicitudTransfusionSanguinea
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solicitud_transfusion_sanguinea_solicitudes_transfusion_sanguinea
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id
    sfGuard_check_created_by: user_id
    AnulableField:         MotivoAnulacion

    config:
      actions: ~
      fields:          
        fecha_prog_quirurgica:     { date_format: dd/MM/yyyy }
        fecha_solicitud:           { label: Fecha, date_format: dd/MM/yyyy }
        fecha_recepcion_solicitud: { date_format: dd/MM/yyyy }
        created_at:                { date_format: dd/MM/yyyy }
        updated_at:                { date_format: dd/MM/yyyy }
        requiere_transfusion_de:               { label: Requiere Transfusion de }
        descripcion_requiere_transfusion_de:   { label: Requiere Transfusion de }
        cumplirse_enforma:                     { label: Cumplirse en Forma }
        descripcion_cumplirse_enforma:         { label: Cumplirse en Forma }
        cantidad_requerida:                    { label: Cantidad}
        cantidad_requerida_unidad:             { label: Unidad}
        grupo_sanguineo_receptor:              { label: Grupo Sanguineo}
        hr_receptor:                           { label: HR}
        nombre_res_bancosangre:                { label: Banco de Sangre}
        creator:                               { label: Responsable }
      list: 
        title:   Listado Solicitud de Tranfusiones sanguineas
        display: [ fecha_solicitud, hora_solicitud, cantidad_requerida, cantidad_requerida_unidad, observaciones, grupo_sanguineo_receptor, hr_receptor, creator]        
        object_actions:  
#          _edit:        { credentials: [noAlta, crear, medico] }
          ver_detalle:  {label: Ver Detalle, action: edit, credentials: [[medico, ver_todo_datos]] }
          _delete:      {label: Anular,  credentials: [noAlta, crear, medico], onClickJsFunction: "dijit.byId('panel_anular').iniciar", AnulableField: 'MotivoAnulacion' }
        actions: {}
        batch_actions: {}
      filter: 
        display: [ fecha_solicitud, grupo_sanguineo_receptor]
      form: 
        display: 
          "&nbsp;": [ internado_id, quirofano ]
          "DIAGNOSTICO:": [ requiere_transfusion_de, cumplirse_enforma ]          
          "TRATAMIENTO AMBULATORIO": [fecha_prog_quirurgica, hora_prog_quirurgica, quirofano_prog_quirurgica, cantidad_requerida, cantidad_requerida_unidad, observaciones, fecha_solicitud, hora_solicitud, numero, fecha_recepcion_solicitud, bolsa_compatible1, bolsa_compatible2, bolsa_compatible3, bolsa_compatible4, bolsa_compatible5, grupo_sanguineo_receptor, hr_receptor, anticuerpos_irreg, nombre_res_bancosangre ]          
        actions:
#          _delete: { credentials: [noAlta, crear, enfermera] }
          _list:   ~
#          _save:   { credentials: [noAlta, crear, enfermera] }
      edit:            
        title: Edición Solicitud de Tranfusiones sanguineas
      new:        
        title: Nueva Solicitud de Tranfusiones sanguineas       
        actions:
          _list:   ~
          _save:   ~