<?php

/**
 * BaseAutorizacionDiagnosticoTratamiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $internado_id
 * @property string $nombre_familiar
 * @property string $ci_familiar
 * @property timestamp $fecha_hora
 * @property Internado $Internado
 * 
 * @method integer                            getInternadoId()     Returns the current record's "internado_id" value
 * @method string                             getNombreFamiliar()  Returns the current record's "nombre_familiar" value
 * @method string                             getCiFamiliar()      Returns the current record's "ci_familiar" value
 * @method timestamp                          getFechaHora()       Returns the current record's "fecha_hora" value
 * @method Internado                          getInternado()       Returns the current record's "Internado" value
 * @method AutorizacionDiagnosticoTratamiento setInternadoId()     Sets the current record's "internado_id" value
 * @method AutorizacionDiagnosticoTratamiento setNombreFamiliar()  Sets the current record's "nombre_familiar" value
 * @method AutorizacionDiagnosticoTratamiento setCiFamiliar()      Sets the current record's "ci_familiar" value
 * @method AutorizacionDiagnosticoTratamiento setFechaHora()       Sets the current record's "fecha_hora" value
 * @method AutorizacionDiagnosticoTratamiento setInternado()       Sets the current record's "Internado" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAutorizacionDiagnosticoTratamiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('autorizacion_diagnostico_tratamiento');
        $this->hasColumn('internado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre_familiar', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('ci_familiar', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('fecha_hora', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Internado', array(
             'local' => 'internado_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}