<?php

/**
 * BasePacienteOtroseguro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $paterno
 * @property string $materno
 * @property string $casada
 * @property date $fechaNacimiento
 * @property string $sexo
 * @property string $ci
 * @property string $exp
 * @property string $domicilio
 * @property string $telefono
 * @property string $celular
 * @property string $email
 * @property string $hclinica
 * @property string $ocupacion
 * @property string $departamento
 * @property string $ciudad
 * @property string $provincia
 * @property Internado $Internado
 * 
 * @method string             getNombre()          Returns the current record's "nombre" value
 * @method string             getPaterno()         Returns the current record's "paterno" value
 * @method string             getMaterno()         Returns the current record's "materno" value
 * @method string             getCasada()          Returns the current record's "casada" value
 * @method date               getFechaNacimiento() Returns the current record's "fechaNacimiento" value
 * @method string             getSexo()            Returns the current record's "sexo" value
 * @method string             getCi()              Returns the current record's "ci" value
 * @method string             getExp()             Returns the current record's "exp" value
 * @method string             getDomicilio()       Returns the current record's "domicilio" value
 * @method string             getTelefono()        Returns the current record's "telefono" value
 * @method string             getCelular()         Returns the current record's "celular" value
 * @method string             getEmail()           Returns the current record's "email" value
 * @method string             getHclinica()        Returns the current record's "hclinica" value
 * @method string             getOcupacion()       Returns the current record's "ocupacion" value
 * @method string             getDepartamento()    Returns the current record's "departamento" value
 * @method string             getCiudad()          Returns the current record's "ciudad" value
 * @method string             getProvincia()       Returns the current record's "provincia" value
 * @method Internado          getInternado()       Returns the current record's "Internado" value
 * @method PacienteOtroseguro setNombre()          Sets the current record's "nombre" value
 * @method PacienteOtroseguro setPaterno()         Sets the current record's "paterno" value
 * @method PacienteOtroseguro setMaterno()         Sets the current record's "materno" value
 * @method PacienteOtroseguro setCasada()          Sets the current record's "casada" value
 * @method PacienteOtroseguro setFechaNacimiento() Sets the current record's "fechaNacimiento" value
 * @method PacienteOtroseguro setSexo()            Sets the current record's "sexo" value
 * @method PacienteOtroseguro setCi()              Sets the current record's "ci" value
 * @method PacienteOtroseguro setExp()             Sets the current record's "exp" value
 * @method PacienteOtroseguro setDomicilio()       Sets the current record's "domicilio" value
 * @method PacienteOtroseguro setTelefono()        Sets the current record's "telefono" value
 * @method PacienteOtroseguro setCelular()         Sets the current record's "celular" value
 * @method PacienteOtroseguro setEmail()           Sets the current record's "email" value
 * @method PacienteOtroseguro setHclinica()        Sets the current record's "hclinica" value
 * @method PacienteOtroseguro setOcupacion()       Sets the current record's "ocupacion" value
 * @method PacienteOtroseguro setDepartamento()    Sets the current record's "departamento" value
 * @method PacienteOtroseguro setCiudad()          Sets the current record's "ciudad" value
 * @method PacienteOtroseguro setProvincia()       Sets the current record's "provincia" value
 * @method PacienteOtroseguro setInternado()       Sets the current record's "Internado" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePacienteOtroseguro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paciente_otroseguro');
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('paterno', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('materno', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('casada', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('fechaNacimiento', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('sexo', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('ci', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 20,
             ));
        $this->hasColumn('exp', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('domicilio', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('telefono', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('celular', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 70, array(
             'type' => 'string',
             'length' => 70,
             ));
        $this->hasColumn('hclinica', 'string', 12, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 12,
             ));
        $this->hasColumn('ocupacion', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('departamento', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('ciudad', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('provincia', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Internado', array(
             'local' => 'id',
             'foreign' => 'noAfiliado_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}