<?php

/**
 * BaseDetalleSolicitudExamenLaboratorioClinico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $solicitud_examen_laboratorio_clinico_id
 * @property integer $tipo_examen_laboratorio_clinico_id
 * @property SolicitudExamenLaboratorioClinico $SolicitudExamenLaboratorioClinico
 * @property TipoExamenLaboratorioClinico $TipoExamenLaboratorioClinico
 * 
 * @method integer                                  getSolicitudExamenLaboratorioClinicoId()     Returns the current record's "solicitud_examen_laboratorio_clinico_id" value
 * @method integer                                  getTipoExamenLaboratorioClinicoId()          Returns the current record's "tipo_examen_laboratorio_clinico_id" value
 * @method SolicitudExamenLaboratorioClinico        getSolicitudExamenLaboratorioClinico()       Returns the current record's "SolicitudExamenLaboratorioClinico" value
 * @method TipoExamenLaboratorioClinico             getTipoExamenLaboratorioClinico()            Returns the current record's "TipoExamenLaboratorioClinico" value
 * @method DetalleSolicitudExamenLaboratorioClinico setSolicitudExamenLaboratorioClinicoId()     Sets the current record's "solicitud_examen_laboratorio_clinico_id" value
 * @method DetalleSolicitudExamenLaboratorioClinico setTipoExamenLaboratorioClinicoId()          Sets the current record's "tipo_examen_laboratorio_clinico_id" value
 * @method DetalleSolicitudExamenLaboratorioClinico setSolicitudExamenLaboratorioClinico()       Sets the current record's "SolicitudExamenLaboratorioClinico" value
 * @method DetalleSolicitudExamenLaboratorioClinico setTipoExamenLaboratorioClinico()            Sets the current record's "TipoExamenLaboratorioClinico" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetalleSolicitudExamenLaboratorioClinico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalle_solicitud_examen_laboratorio_clinico');
        $this->hasColumn('solicitud_examen_laboratorio_clinico_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo_examen_laboratorio_clinico_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SolicitudExamenLaboratorioClinico', array(
             'local' => 'solicitud_examen_laboratorio_clinico_id',
             'foreign' => 'id'));

        $this->hasOne('TipoExamenLaboratorioClinico', array(
             'local' => 'tipo_examen_laboratorio_clinico_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}