<?php

/**
 * BaseTipoExamenLaboratorioClinico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $grupo_orden
 * @property string $grupo_nombre
 * @property string $examen_orden
 * @property string $examen_nombre
 * @property boolean $activo
 * @property Doctrine_Collection $SolicitudExamenLaboratorioClinico
 * @property Doctrine_Collection $DetalleSolicitudExamenLaboratorioClinico
 * 
 * @method integer                      getGrupoOrden()                               Returns the current record's "grupo_orden" value
 * @method string                       getGrupoNombre()                              Returns the current record's "grupo_nombre" value
 * @method string                       getExamenOrden()                              Returns the current record's "examen_orden" value
 * @method string                       getExamenNombre()                             Returns the current record's "examen_nombre" value
 * @method boolean                      getActivo()                                   Returns the current record's "activo" value
 * @method Doctrine_Collection          getSolicitudExamenLaboratorioClinico()        Returns the current record's "SolicitudExamenLaboratorioClinico" collection
 * @method Doctrine_Collection          getDetalleSolicitudExamenLaboratorioClinico() Returns the current record's "DetalleSolicitudExamenLaboratorioClinico" collection
 * @method TipoExamenLaboratorioClinico setGrupoOrden()                               Sets the current record's "grupo_orden" value
 * @method TipoExamenLaboratorioClinico setGrupoNombre()                              Sets the current record's "grupo_nombre" value
 * @method TipoExamenLaboratorioClinico setExamenOrden()                              Sets the current record's "examen_orden" value
 * @method TipoExamenLaboratorioClinico setExamenNombre()                             Sets the current record's "examen_nombre" value
 * @method TipoExamenLaboratorioClinico setActivo()                                   Sets the current record's "activo" value
 * @method TipoExamenLaboratorioClinico setSolicitudExamenLaboratorioClinico()        Sets the current record's "SolicitudExamenLaboratorioClinico" collection
 * @method TipoExamenLaboratorioClinico setDetalleSolicitudExamenLaboratorioClinico() Sets the current record's "DetalleSolicitudExamenLaboratorioClinico" collection
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoExamenLaboratorioClinico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_examen_laboratorio_clinico');
        $this->hasColumn('grupo_orden', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 3,
             ));
        $this->hasColumn('grupo_nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('examen_orden', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('examen_nombre', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SolicitudExamenLaboratorioClinico', array(
             'refClass' => 'DetalleSolicitudExamenLaboratorioClinico',
             'local' => 'tipo_examen_laboratorio_clinico_id',
             'foreign' => 'solicitud_examen_laboratorio_clinico_id'));

        $this->hasMany('DetalleSolicitudExamenLaboratorioClinico', array(
             'local' => 'id',
             'foreign' => 'tipo_examen_laboratorio_clinico_id'));
    }
}