<?php

/**
 * BaseFileInternacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $internado_id
 * @property Internado $Internado
 * 
 * @method integer         getInternadoId()  Returns the current record's "internado_id" value
 * @method Internado       getInternado()    Returns the current record's "Internado" value
 * @method FileInternacion setInternadoId()  Sets the current record's "internado_id" value
 * @method FileInternacion setInternado()    Sets the current record's "Internado" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFileInternacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file_internacion');
        $this->hasColumn('internado_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Internado', array(
             'local' => 'internado_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}