<?php

/**
 * BaseDetalleSolicitudExamenLaboratorio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $solicitud_examen_laboratorio_id
 * @property integer $tipo
 * @property SolicitudExamenLaboratorio $SolicitudExamenLaboratorio
 * 
 * @method integer                           getSolicitudExamenLaboratorioId()    Returns the current record's "solicitud_examen_laboratorio_id" value
 * @method integer                           getTipo()                            Returns the current record's "tipo" value
 * @method SolicitudExamenLaboratorio        getSolicitudExamenLaboratorio()      Returns the current record's "SolicitudExamenLaboratorio" value
 * @method DetalleSolicitudExamenLaboratorio setSolicitudExamenLaboratorioId()    Sets the current record's "solicitud_examen_laboratorio_id" value
 * @method DetalleSolicitudExamenLaboratorio setTipo()                            Sets the current record's "tipo" value
 * @method DetalleSolicitudExamenLaboratorio setSolicitudExamenLaboratorio()      Sets the current record's "SolicitudExamenLaboratorio" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetalleSolicitudExamenLaboratorio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalle_solicitud_examen_laboratorio');
        $this->hasColumn('solicitud_examen_laboratorio_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SolicitudExamenLaboratorio', array(
             'local' => 'solicitud_examen_laboratorio_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}