<?php

/**
 * BaseDetalleUsoHospitalario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $uso_hospitalario_id
 * @property string $codigo_cbm
 * @property string $detalle
 * @property integer $cantidad
 * @property string $unidad
 * @property string $cod_farmacia_ibm
 * @property UsoHospitalario $UsoHospitalario
 * 
 * @method integer                getUsoHospitalarioId()   Returns the current record's "uso_hospitalario_id" value
 * @method string                 getCodigoCbm()           Returns the current record's "codigo_cbm" value
 * @method string                 getDetalle()             Returns the current record's "detalle" value
 * @method integer                getCantidad()            Returns the current record's "cantidad" value
 * @method string                 getUnidad()              Returns the current record's "unidad" value
 * @method string                 getCodFarmaciaIbm()      Returns the current record's "cod_farmacia_ibm" value
 * @method UsoHospitalario        getUsoHospitalario()     Returns the current record's "UsoHospitalario" value
 * @method DetalleUsoHospitalario setUsoHospitalarioId()   Sets the current record's "uso_hospitalario_id" value
 * @method DetalleUsoHospitalario setCodigoCbm()           Sets the current record's "codigo_cbm" value
 * @method DetalleUsoHospitalario setDetalle()             Sets the current record's "detalle" value
 * @method DetalleUsoHospitalario setCantidad()            Sets the current record's "cantidad" value
 * @method DetalleUsoHospitalario setUnidad()              Sets the current record's "unidad" value
 * @method DetalleUsoHospitalario setCodFarmaciaIbm()      Sets the current record's "cod_farmacia_ibm" value
 * @method DetalleUsoHospitalario setUsoHospitalario()     Sets the current record's "UsoHospitalario" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetalleUsoHospitalario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalle_uso_hospitalario');
        $this->hasColumn('uso_hospitalario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('codigo_cbm', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('detalle', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('cantidad', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('unidad', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('cod_farmacia_ibm', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UsoHospitalario', array(
             'local' => 'uso_hospitalario_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}