<?php

/**
 * BaseNotasEnfermeria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $internado_id
 * @property date $fecha
 * @property time $hora
 * @property string $procedimientos
 * @property string $observaciones
 * @property Internado $Internado
 * 
 * @method integer         getInternadoId()    Returns the current record's "internado_id" value
 * @method date            getFecha()          Returns the current record's "fecha" value
 * @method time            getHora()           Returns the current record's "hora" value
 * @method string          getProcedimientos() Returns the current record's "procedimientos" value
 * @method string          getObservaciones()  Returns the current record's "observaciones" value
 * @method Internado       getInternado()      Returns the current record's "Internado" value
 * @method NotasEnfermeria setInternadoId()    Sets the current record's "internado_id" value
 * @method NotasEnfermeria setFecha()          Sets the current record's "fecha" value
 * @method NotasEnfermeria setHora()           Sets the current record's "hora" value
 * @method NotasEnfermeria setProcedimientos() Sets the current record's "procedimientos" value
 * @method NotasEnfermeria setObservaciones()  Sets the current record's "observaciones" value
 * @method NotasEnfermeria setInternado()      Sets the current record's "Internado" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotasEnfermeria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notas_enfermeria');
        $this->hasColumn('internado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('hora', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('procedimientos', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('observaciones', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Internado', array(
             'local' => 'internado_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}