<?php

/**
 * BaseDetalleAdminMedicamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $administracion_medicamento_id
 * @property integer $enfermera_id
 * @property string $medicamento_solucion
 * @property string $tipo
 * @property date $fecha
 * @property time $horario
 * @property AdministracionMedicamento $AdministracionMedicamento
 * 
 * @method integer                   getAdministracionMedicamentoId()   Returns the current record's "administracion_medicamento_id" value
 * @method integer                   getEnfermeraId()                   Returns the current record's "enfermera_id" value
 * @method string                    getMedicamentoSolucion()           Returns the current record's "medicamento_solucion" value
 * @method string                    getTipo()                          Returns the current record's "tipo" value
 * @method date                      getFecha()                         Returns the current record's "fecha" value
 * @method time                      getHorario()                       Returns the current record's "horario" value
 * @method AdministracionMedicamento getAdministracionMedicamento()     Returns the current record's "AdministracionMedicamento" value
 * @method DetalleAdminMedicamento   setAdministracionMedicamentoId()   Sets the current record's "administracion_medicamento_id" value
 * @method DetalleAdminMedicamento   setEnfermeraId()                   Sets the current record's "enfermera_id" value
 * @method DetalleAdminMedicamento   setMedicamentoSolucion()           Sets the current record's "medicamento_solucion" value
 * @method DetalleAdminMedicamento   setTipo()                          Sets the current record's "tipo" value
 * @method DetalleAdminMedicamento   setFecha()                         Sets the current record's "fecha" value
 * @method DetalleAdminMedicamento   setHorario()                       Sets the current record's "horario" value
 * @method DetalleAdminMedicamento   setAdministracionMedicamento()     Sets the current record's "AdministracionMedicamento" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetalleAdminMedicamento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalle_admin_medicamento');
        $this->hasColumn('administracion_medicamento_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('enfermera_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('medicamento_solucion', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('tipo', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('horario', 'time', null, array(
             'type' => 'time',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AdministracionMedicamento', array(
             'local' => 'administracion_medicamento_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}