<?php

/**
 * BaseCama
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pieza_id
 * @property string $codigo
 * @property boolean $ocupada
 * @property string $observaciones
 * @property string $codigo_activo
 * @property integer $activo_id
 * @property Pieza $Pieza
 * @property Doctrine_Collection $Internado
 * 
 * @method integer             getPiezaId()       Returns the current record's "pieza_id" value
 * @method string              getCodigo()        Returns the current record's "codigo" value
 * @method boolean             getOcupada()       Returns the current record's "ocupada" value
 * @method string              getObservaciones() Returns the current record's "observaciones" value
 * @method string              getCodigoActivo()  Returns the current record's "codigo_activo" value
 * @method integer             getActivoId()      Returns the current record's "activo_id" value
 * @method Pieza               getPieza()         Returns the current record's "Pieza" value
 * @method Doctrine_Collection getInternado()     Returns the current record's "Internado" collection
 * @method Cama                setPiezaId()       Sets the current record's "pieza_id" value
 * @method Cama                setCodigo()        Sets the current record's "codigo" value
 * @method Cama                setOcupada()       Sets the current record's "ocupada" value
 * @method Cama                setObservaciones() Sets the current record's "observaciones" value
 * @method Cama                setCodigoActivo()  Sets the current record's "codigo_activo" value
 * @method Cama                setActivoId()      Sets the current record's "activo_id" value
 * @method Cama                setPieza()         Sets the current record's "Pieza" value
 * @method Cama                setInternado()     Sets the current record's "Internado" collection
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCama extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cama');
        $this->hasColumn('pieza_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('codigo', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('ocupada', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('observaciones', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('codigo_activo', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('activo_id', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pieza', array(
             'local' => 'pieza_id',
             'foreign' => 'id'));

        $this->hasMany('Internado', array(
             'local' => 'id',
             'foreign' => 'cama_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}