<?php

/**
 * BaseResumenAlta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $internado_id
 * @property string $diagnostico_provisional
 * @property string $diagnostico_definitivo
 * @property string $operaciones
 * @property string $anamesis_examenfisico
 * @property string $hallazgos_labo_interconsultas
 * @property string $evolucion_complicacion
 * @property string $condicion_tratamiento_pronostico
 * @property Internado $Internado
 * 
 * @method integer     getInternadoId()                      Returns the current record's "internado_id" value
 * @method string      getDiagnosticoProvisional()           Returns the current record's "diagnostico_provisional" value
 * @method string      getDiagnosticoDefinitivo()            Returns the current record's "diagnostico_definitivo" value
 * @method string      getOperaciones()                      Returns the current record's "operaciones" value
 * @method string      getAnamesisExamenfisico()             Returns the current record's "anamesis_examenfisico" value
 * @method string      getHallazgosLaboInterconsultas()      Returns the current record's "hallazgos_labo_interconsultas" value
 * @method string      getEvolucionComplicacion()            Returns the current record's "evolucion_complicacion" value
 * @method string      getCondicionTratamientoPronostico()   Returns the current record's "condicion_tratamiento_pronostico" value
 * @method Internado   getInternado()                        Returns the current record's "Internado" value
 * @method ResumenAlta setInternadoId()                      Sets the current record's "internado_id" value
 * @method ResumenAlta setDiagnosticoProvisional()           Sets the current record's "diagnostico_provisional" value
 * @method ResumenAlta setDiagnosticoDefinitivo()            Sets the current record's "diagnostico_definitivo" value
 * @method ResumenAlta setOperaciones()                      Sets the current record's "operaciones" value
 * @method ResumenAlta setAnamesisExamenfisico()             Sets the current record's "anamesis_examenfisico" value
 * @method ResumenAlta setHallazgosLaboInterconsultas()      Sets the current record's "hallazgos_labo_interconsultas" value
 * @method ResumenAlta setEvolucionComplicacion()            Sets the current record's "evolucion_complicacion" value
 * @method ResumenAlta setCondicionTratamientoPronostico()   Sets the current record's "condicion_tratamiento_pronostico" value
 * @method ResumenAlta setInternado()                        Sets the current record's "Internado" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResumenAlta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('resumen_alta');
        $this->hasColumn('internado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('diagnostico_provisional', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('diagnostico_definitivo', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('operaciones', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('anamesis_examenfisico', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('hallazgos_labo_interconsultas', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('evolucion_complicacion', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('condicion_tratamiento_pronostico', 'string', 8000, array(
             'type' => 'string',
             'length' => 8000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Internado', array(
             'local' => 'internado_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $anulablebehavior0 = new AnulableBehavior(array(
             'type' => 'string',
             'length' => 200,
             'name' => 'motivo_anulacion',
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($anulablebehavior0);
    }
}