<?php

/**
 * BaseOrdenMedica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $internado_id
 * @property integer $via_administracion_id
 * @property timestamp $fecha_hora
 * @property string $nombre_medicamento
 * @property string $indicacion
 * @property string $dosis_intervalo
 * @property date $fecha_inicio
 * @property date $fecha_terminacion
 * @property Internado $Internado
 * @property ViaAdministracion $ViaAdministracion
 * 
 * @method integer           getInternadoId()           Returns the current record's "internado_id" value
 * @method integer           getViaAdministracionId()   Returns the current record's "via_administracion_id" value
 * @method timestamp         getFechaHora()             Returns the current record's "fecha_hora" value
 * @method string            getNombreMedicamento()     Returns the current record's "nombre_medicamento" value
 * @method string            getIndicacion()            Returns the current record's "indicacion" value
 * @method string            getDosisIntervalo()        Returns the current record's "dosis_intervalo" value
 * @method date              getFechaInicio()           Returns the current record's "fecha_inicio" value
 * @method date              getFechaTerminacion()      Returns the current record's "fecha_terminacion" value
 * @method Internado         getInternado()             Returns the current record's "Internado" value
 * @method ViaAdministracion getViaAdministracion()     Returns the current record's "ViaAdministracion" value
 * @method OrdenMedica       setInternadoId()           Sets the current record's "internado_id" value
 * @method OrdenMedica       setViaAdministracionId()   Sets the current record's "via_administracion_id" value
 * @method OrdenMedica       setFechaHora()             Sets the current record's "fecha_hora" value
 * @method OrdenMedica       setNombreMedicamento()     Sets the current record's "nombre_medicamento" value
 * @method OrdenMedica       setIndicacion()            Sets the current record's "indicacion" value
 * @method OrdenMedica       setDosisIntervalo()        Sets the current record's "dosis_intervalo" value
 * @method OrdenMedica       setFechaInicio()           Sets the current record's "fecha_inicio" value
 * @method OrdenMedica       setFechaTerminacion()      Sets the current record's "fecha_terminacion" value
 * @method OrdenMedica       setInternado()             Sets the current record's "Internado" value
 * @method OrdenMedica       setViaAdministracion()     Sets the current record's "ViaAdministracion" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrdenMedica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orden_medica');
        $this->hasColumn('internado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('via_administracion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fecha_hora', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('nombre_medicamento', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('indicacion', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('dosis_intervalo', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('fecha_inicio', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('fecha_terminacion', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Internado', array(
             'local' => 'internado_id',
             'foreign' => 'id'));

        $this->hasOne('ViaAdministracion', array(
             'local' => 'via_administracion_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $anulablebehavior0 = new AnulableBehavior(array(
             'type' => 'string',
             'length' => 200,
             'name' => 'motivo_anulacion',
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($anulablebehavior0);
    }
}