<?php

/**
 * BaseDetallePapeletaPedidoMaterial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $papeleta_pedido_material_id
 * @property string $columna1
 * @property string $columna2
 * @property string $columna3
 * @property PapeletaPedidoMaterial $PapeletaPedidoMaterial
 * 
 * @method integer                       getPapeletaPedidoMaterialId()    Returns the current record's "papeleta_pedido_material_id" value
 * @method string                        getColumna1()                    Returns the current record's "columna1" value
 * @method string                        getColumna2()                    Returns the current record's "columna2" value
 * @method string                        getColumna3()                    Returns the current record's "columna3" value
 * @method PapeletaPedidoMaterial        getPapeletaPedidoMaterial()      Returns the current record's "PapeletaPedidoMaterial" value
 * @method DetallePapeletaPedidoMaterial setPapeletaPedidoMaterialId()    Sets the current record's "papeleta_pedido_material_id" value
 * @method DetallePapeletaPedidoMaterial setColumna1()                    Sets the current record's "columna1" value
 * @method DetallePapeletaPedidoMaterial setColumna2()                    Sets the current record's "columna2" value
 * @method DetallePapeletaPedidoMaterial setColumna3()                    Sets the current record's "columna3" value
 * @method DetallePapeletaPedidoMaterial setPapeletaPedidoMaterial()      Sets the current record's "PapeletaPedidoMaterial" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetallePapeletaPedidoMaterial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalle_papeleta_pedido_material');
        $this->hasColumn('papeleta_pedido_material_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('columna1', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 15,
             ));
        $this->hasColumn('columna2', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('columna3', 'string', 25, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PapeletaPedidoMaterial', array(
             'local' => 'papeleta_pedido_material_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}