<?php

/**
 * BaseUsoHospitalario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $file_internacion_id
 * @property integer $medico_id
 * @property string $lugar
 * @property string $codigo
 * @property string $especialidad
 * @property FileInternacion $FileInternacion
 * @property Doctrine_Collection $UsoHospitalario
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method integer             getFileInternacionId()   Returns the current record's "file_internacion_id" value
 * @method integer             getMedicoId()            Returns the current record's "medico_id" value
 * @method string              getLugar()               Returns the current record's "lugar" value
 * @method string              getCodigo()              Returns the current record's "codigo" value
 * @method string              getEspecialidad()        Returns the current record's "especialidad" value
 * @method FileInternacion     getFileInternacion()     Returns the current record's "FileInternacion" value
 * @method Doctrine_Collection getUsoHospitalario()     Returns the current record's "UsoHospitalario" collection
 * @method UsoHospitalario     setId()                  Sets the current record's "id" value
 * @method UsoHospitalario     setFileInternacionId()   Sets the current record's "file_internacion_id" value
 * @method UsoHospitalario     setMedicoId()            Sets the current record's "medico_id" value
 * @method UsoHospitalario     setLugar()               Sets the current record's "lugar" value
 * @method UsoHospitalario     setCodigo()              Sets the current record's "codigo" value
 * @method UsoHospitalario     setEspecialidad()        Sets the current record's "especialidad" value
 * @method UsoHospitalario     setFileInternacion()     Sets the current record's "FileInternacion" value
 * @method UsoHospitalario     setUsoHospitalario()     Sets the current record's "UsoHospitalario" collection
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsoHospitalario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('uso_hospitalario');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('file_internacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('medico_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('lugar', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('codigo', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('especialidad', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FileInternacion', array(
             'local' => 'file_internacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('DetalleUsoHospitalario as UsoHospitalario', array(
             'local' => 'id',
             'foreign' => 'uso_hospitalario_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}