<?php

/**
 * BaseDetalleEnfermeria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $notas_enfermeria_id
 * @property date $fecha
 * @property time $hora
 * @property string $procedimientos
 * @property string $observaciones
 * @property NotasEnfermeria $NotasEnfermeria
 * 
 * @method integer           getNotasEnfermeriaId()   Returns the current record's "notas_enfermeria_id" value
 * @method date              getFecha()               Returns the current record's "fecha" value
 * @method time              getHora()                Returns the current record's "hora" value
 * @method string            getProcedimientos()      Returns the current record's "procedimientos" value
 * @method string            getObservaciones()       Returns the current record's "observaciones" value
 * @method NotasEnfermeria   getNotasEnfermeria()     Returns the current record's "NotasEnfermeria" value
 * @method DetalleEnfermeria setNotasEnfermeriaId()   Sets the current record's "notas_enfermeria_id" value
 * @method DetalleEnfermeria setFecha()               Sets the current record's "fecha" value
 * @method DetalleEnfermeria setHora()                Sets the current record's "hora" value
 * @method DetalleEnfermeria setProcedimientos()      Sets the current record's "procedimientos" value
 * @method DetalleEnfermeria setObservaciones()       Sets the current record's "observaciones" value
 * @method DetalleEnfermeria setNotasEnfermeria()     Sets the current record's "NotasEnfermeria" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetalleEnfermeria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalle_enfermeria');
        $this->hasColumn('notas_enfermeria_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('hora', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('procedimientos', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('observaciones', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NotasEnfermeria', array(
             'local' => 'notas_enfermeria_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}