<?php

/**
 * BaseApgar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $examen_fisico_recien_nacido_id
 * @property boolean $nacer_egresar
 * @property string $apariencia
 * @property string $piel
 * @property string $cabeza
 * @property string $ojos
 * @property string $oidos_nariz_garganta
 * @property string $torax
 * @property string $pulmones
 * @property string $corazon
 * @property string $abdomen
 * @property string $genitales
 * @property string $torso_espina
 * @property string $extremidades
 * @property string $reflejos
 * @property string $ano
 * @property ExamenFisicoRecienNacido $ExamenFisicoRecienNacido
 * 
 * @method integer                  getExamenFisicoRecienNacidoId()     Returns the current record's "examen_fisico_recien_nacido_id" value
 * @method boolean                  getNacerEgresar()                   Returns the current record's "nacer_egresar" value
 * @method string                   getApariencia()                     Returns the current record's "apariencia" value
 * @method string                   getPiel()                           Returns the current record's "piel" value
 * @method string                   getCabeza()                         Returns the current record's "cabeza" value
 * @method string                   getOjos()                           Returns the current record's "ojos" value
 * @method string                   getOidosNarizGarganta()             Returns the current record's "oidos_nariz_garganta" value
 * @method string                   getTorax()                          Returns the current record's "torax" value
 * @method string                   getPulmones()                       Returns the current record's "pulmones" value
 * @method string                   getCorazon()                        Returns the current record's "corazon" value
 * @method string                   getAbdomen()                        Returns the current record's "abdomen" value
 * @method string                   getGenitales()                      Returns the current record's "genitales" value
 * @method string                   getTorsoEspina()                    Returns the current record's "torso_espina" value
 * @method string                   getExtremidades()                   Returns the current record's "extremidades" value
 * @method string                   getReflejos()                       Returns the current record's "reflejos" value
 * @method string                   getAno()                            Returns the current record's "ano" value
 * @method ExamenFisicoRecienNacido getExamenFisicoRecienNacido()       Returns the current record's "ExamenFisicoRecienNacido" value
 * @method Apgar                    setExamenFisicoRecienNacidoId()     Sets the current record's "examen_fisico_recien_nacido_id" value
 * @method Apgar                    setNacerEgresar()                   Sets the current record's "nacer_egresar" value
 * @method Apgar                    setApariencia()                     Sets the current record's "apariencia" value
 * @method Apgar                    setPiel()                           Sets the current record's "piel" value
 * @method Apgar                    setCabeza()                         Sets the current record's "cabeza" value
 * @method Apgar                    setOjos()                           Sets the current record's "ojos" value
 * @method Apgar                    setOidosNarizGarganta()             Sets the current record's "oidos_nariz_garganta" value
 * @method Apgar                    setTorax()                          Sets the current record's "torax" value
 * @method Apgar                    setPulmones()                       Sets the current record's "pulmones" value
 * @method Apgar                    setCorazon()                        Sets the current record's "corazon" value
 * @method Apgar                    setAbdomen()                        Sets the current record's "abdomen" value
 * @method Apgar                    setGenitales()                      Sets the current record's "genitales" value
 * @method Apgar                    setTorsoEspina()                    Sets the current record's "torso_espina" value
 * @method Apgar                    setExtremidades()                   Sets the current record's "extremidades" value
 * @method Apgar                    setReflejos()                       Sets the current record's "reflejos" value
 * @method Apgar                    setAno()                            Sets the current record's "ano" value
 * @method Apgar                    setExamenFisicoRecienNacido()       Sets the current record's "ExamenFisicoRecienNacido" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApgar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('apgar');
        $this->hasColumn('examen_fisico_recien_nacido_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nacer_egresar', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('apariencia', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('piel', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('cabeza', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('ojos', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('oidos_nariz_garganta', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('torax', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('pulmones', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('corazon', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('abdomen', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('genitales', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('torso_espina', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('extremidades', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('reflejos', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('ano', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ExamenFisicoRecienNacido', array(
             'local' => 'examen_fisico_recien_nacido_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}