<?php

/**
 * BaseNotasEvolucion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $internado_id
 * @property timestamp $fecha_hora
 * @property integer $numero_prob
 * @property string $nota_soap
 * @property Internado $Internado
 * 
 * @method integer        getInternadoId()  Returns the current record's "internado_id" value
 * @method timestamp      getFechaHora()    Returns the current record's "fecha_hora" value
 * @method integer        getNumeroProb()   Returns the current record's "numero_prob" value
 * @method string         getNotaSoap()     Returns the current record's "nota_soap" value
 * @method Internado      getInternado()    Returns the current record's "Internado" value
 * @method NotasEvolucion setInternadoId()  Sets the current record's "internado_id" value
 * @method NotasEvolucion setFechaHora()    Sets the current record's "fecha_hora" value
 * @method NotasEvolucion setNumeroProb()   Sets the current record's "numero_prob" value
 * @method NotasEvolucion setNotaSoap()     Sets the current record's "nota_soap" value
 * @method NotasEvolucion setInternado()    Sets the current record's "Internado" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotasEvolucion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notas_evolucion');
        $this->hasColumn('internado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fecha_hora', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('numero_prob', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nota_soap', 'string', 1500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Internado', array(
             'local' => 'internado_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}