<?php

/**
 * BaseDetalleMedicacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $solicitud_interconsulta_id
 * @property string $medicacion_utilizada
 * @property string $dosis
 * @property date $fecha_inicio
 * @property SolicitudInterconsulta $SolicitudInterconsulta
 * 
 * @method integer                getSolicitudInterconsultaId()   Returns the current record's "solicitud_interconsulta_id" value
 * @method string                 getMedicacionUtilizada()        Returns the current record's "medicacion_utilizada" value
 * @method string                 getDosis()                      Returns the current record's "dosis" value
 * @method date                   getFechaInicio()                Returns the current record's "fecha_inicio" value
 * @method SolicitudInterconsulta getSolicitudInterconsulta()     Returns the current record's "SolicitudInterconsulta" value
 * @method DetalleMedicacion      setSolicitudInterconsultaId()   Sets the current record's "solicitud_interconsulta_id" value
 * @method DetalleMedicacion      setMedicacionUtilizada()        Sets the current record's "medicacion_utilizada" value
 * @method DetalleMedicacion      setDosis()                      Sets the current record's "dosis" value
 * @method DetalleMedicacion      setFechaInicio()                Sets the current record's "fecha_inicio" value
 * @method DetalleMedicacion      setSolicitudInterconsulta()     Sets the current record's "SolicitudInterconsulta" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetalleMedicacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalle_medicacion');
        $this->hasColumn('solicitud_interconsulta_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('medicacion_utilizada', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('dosis', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('fecha_inicio', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SolicitudInterconsulta', array(
             'local' => 'solicitud_interconsulta_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}