<?php

/**
 * BaseAdministracionMedicamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $file_internacion_id
 * @property FileInternacion $FileInternacion
 * @property Doctrine_Collection $AdministracionMedicamento
 * 
 * @method integer                   getId()                        Returns the current record's "id" value
 * @method integer                   getFileInternacionId()         Returns the current record's "file_internacion_id" value
 * @method FileInternacion           getFileInternacion()           Returns the current record's "FileInternacion" value
 * @method Doctrine_Collection       getAdministracionMedicamento() Returns the current record's "AdministracionMedicamento" collection
 * @method AdministracionMedicamento setId()                        Sets the current record's "id" value
 * @method AdministracionMedicamento setFileInternacionId()         Sets the current record's "file_internacion_id" value
 * @method AdministracionMedicamento setFileInternacion()           Sets the current record's "FileInternacion" value
 * @method AdministracionMedicamento setAdministracionMedicamento() Sets the current record's "AdministracionMedicamento" collection
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdministracionMedicamento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('administracion_medicamento');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('file_internacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FileInternacion', array(
             'local' => 'file_internacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('DetalleAdminMedicamento as AdministracionMedicamento', array(
             'local' => 'id',
             'foreign' => 'administracion_medicamento_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}