<?php

/**
 * BaseDetalleListaDieta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $lista_dieta_id
 * @property integer $internado_id
 * @property string $dieta
 * @property string $diagnostico
 * @property Internado $Internado
 * @property ListaDieta $ListaDieta
 * 
 * @method integer           getListaDietaId()   Returns the current record's "lista_dieta_id" value
 * @method integer           getInternadoId()    Returns the current record's "internado_id" value
 * @method string            getDieta()          Returns the current record's "dieta" value
 * @method string            getDiagnostico()    Returns the current record's "diagnostico" value
 * @method Internado         getInternado()      Returns the current record's "Internado" value
 * @method ListaDieta        getListaDieta()     Returns the current record's "ListaDieta" value
 * @method DetalleListaDieta setListaDietaId()   Sets the current record's "lista_dieta_id" value
 * @method DetalleListaDieta setInternadoId()    Sets the current record's "internado_id" value
 * @method DetalleListaDieta setDieta()          Sets the current record's "dieta" value
 * @method DetalleListaDieta setDiagnostico()    Sets the current record's "diagnostico" value
 * @method DetalleListaDieta setInternado()      Sets the current record's "Internado" value
 * @method DetalleListaDieta setListaDieta()     Sets the current record's "ListaDieta" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetalleListaDieta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalle_lista_dieta');
        $this->hasColumn('lista_dieta_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('internado_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dieta', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('diagnostico', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Internado', array(
             'local' => 'internado_id',
             'foreign' => 'id'));

        $this->hasOne('ListaDieta', array(
             'local' => 'lista_dieta_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}