<?php

/**
 * BaseListaDieta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $internado_id
 * @property integer $enfermera_id
 * @property integer $servicio_id
 * @property date $fecha
 * @property string $dieta
 * @property string $diagnostico
 * @property string $observacion
 * @property Internado $Internado
 * 
 * @method integer    getInternadoId()  Returns the current record's "internado_id" value
 * @method integer    getEnfermeraId()  Returns the current record's "enfermera_id" value
 * @method integer    getServicioId()   Returns the current record's "servicio_id" value
 * @method date       getFecha()        Returns the current record's "fecha" value
 * @method string     getDieta()        Returns the current record's "dieta" value
 * @method string     getDiagnostico()  Returns the current record's "diagnostico" value
 * @method string     getObservacion()  Returns the current record's "observacion" value
 * @method Internado  getInternado()    Returns the current record's "Internado" value
 * @method ListaDieta setInternadoId()  Sets the current record's "internado_id" value
 * @method ListaDieta setEnfermeraId()  Sets the current record's "enfermera_id" value
 * @method ListaDieta setServicioId()   Sets the current record's "servicio_id" value
 * @method ListaDieta setFecha()        Sets the current record's "fecha" value
 * @method ListaDieta setDieta()        Sets the current record's "dieta" value
 * @method ListaDieta setDiagnostico()  Sets the current record's "diagnostico" value
 * @method ListaDieta setObservacion()  Sets the current record's "observacion" value
 * @method ListaDieta setInternado()    Sets the current record's "Internado" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseListaDieta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lista_dieta');
        $this->hasColumn('internado_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('enfermera_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('servicio_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('dieta', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('diagnostico', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('observacion', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Internado', array(
             'local' => 'internado_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $borradocontipomotivobehavior0 = new BorradoConTipoMotivoBehavior(array(
             'name' => 'motivo_borrado',
             'type' => 'string',
             'swname' => 'tipo_borrado',
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($borradocontipomotivobehavior0);
    }
}