<?php

/**
 * BaseJuntaMedica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $internado_id
 * @property integer $medico_id
 * @property string $servicio
 * @property string $especialidades
 * @property date $fecha_junta
 * @property string $diagnostico_establecido
 * @property string $relacion_junta
 * @property string $conclusiones
 * @property boolean $tac
 * @property boolean $contraste
 * @property Internado $Internado
 * @property Doctrine_Collection $MedicoParticipante
 * @property Medico $Medico
 * 
 * @method integer             getInternadoId()             Returns the current record's "internado_id" value
 * @method integer             getMedicoId()                Returns the current record's "medico_id" value
 * @method string              getServicio()                Returns the current record's "servicio" value
 * @method string              getEspecialidades()          Returns the current record's "especialidades" value
 * @method date                getFechaJunta()              Returns the current record's "fecha_junta" value
 * @method string              getDiagnosticoEstablecido()  Returns the current record's "diagnostico_establecido" value
 * @method string              getRelacionJunta()           Returns the current record's "relacion_junta" value
 * @method string              getConclusiones()            Returns the current record's "conclusiones" value
 * @method boolean             getTac()                     Returns the current record's "tac" value
 * @method boolean             getContraste()               Returns the current record's "contraste" value
 * @method Internado           getInternado()               Returns the current record's "Internado" value
 * @method Doctrine_Collection getMedicoParticipante()      Returns the current record's "MedicoParticipante" collection
 * @method Medico              getMedico()                  Returns the current record's "Medico" value
 * @method JuntaMedica         setInternadoId()             Sets the current record's "internado_id" value
 * @method JuntaMedica         setMedicoId()                Sets the current record's "medico_id" value
 * @method JuntaMedica         setServicio()                Sets the current record's "servicio" value
 * @method JuntaMedica         setEspecialidades()          Sets the current record's "especialidades" value
 * @method JuntaMedica         setFechaJunta()              Sets the current record's "fecha_junta" value
 * @method JuntaMedica         setDiagnosticoEstablecido()  Sets the current record's "diagnostico_establecido" value
 * @method JuntaMedica         setRelacionJunta()           Sets the current record's "relacion_junta" value
 * @method JuntaMedica         setConclusiones()            Sets the current record's "conclusiones" value
 * @method JuntaMedica         setTac()                     Sets the current record's "tac" value
 * @method JuntaMedica         setContraste()               Sets the current record's "contraste" value
 * @method JuntaMedica         setInternado()               Sets the current record's "Internado" value
 * @method JuntaMedica         setMedicoParticipante()      Sets the current record's "MedicoParticipante" collection
 * @method JuntaMedica         setMedico()                  Sets the current record's "Medico" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJuntaMedica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('junta_medica');
        $this->hasColumn('internado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('medico_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('servicio', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('especialidades', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('fecha_junta', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('diagnostico_establecido', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('relacion_junta', 'string', 2500, array(
             'type' => 'string',
             'length' => 2500,
             ));
        $this->hasColumn('conclusiones', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('tac', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('contraste', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Internado', array(
             'local' => 'internado_id',
             'foreign' => 'id'));

        $this->hasMany('MedicoParticipante', array(
             'local' => 'id',
             'foreign' => 'junta_medica_id'));

        $this->hasOne('Medico', array(
             'local' => 'medico_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}