<?php

/**
 * BaseFilial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $direccion
 * @property string $telefono
 * @property string $telefono2
 * @property string $telefono3
 * @property string $descripcion
 * @property string $codigo
 * @property string $geoubicacion
 * @property string $geoubicacion2
 * @property Doctrine_Collection $Planta
 * @property Doctrine_Collection $Empleados
 * 
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method string              getDireccion()     Returns the current record's "direccion" value
 * @method string              getTelefono()      Returns the current record's "telefono" value
 * @method string              getTelefono2()     Returns the current record's "telefono2" value
 * @method string              getTelefono3()     Returns the current record's "telefono3" value
 * @method string              getDescripcion()   Returns the current record's "descripcion" value
 * @method string              getCodigo()        Returns the current record's "codigo" value
 * @method string              getGeoubicacion()  Returns the current record's "geoubicacion" value
 * @method string              getGeoubicacion2() Returns the current record's "geoubicacion2" value
 * @method Doctrine_Collection getPlanta()        Returns the current record's "Planta" collection
 * @method Doctrine_Collection getEmpleados()     Returns the current record's "Empleados" collection
 * @method Filial              setNombre()        Sets the current record's "nombre" value
 * @method Filial              setDireccion()     Sets the current record's "direccion" value
 * @method Filial              setTelefono()      Sets the current record's "telefono" value
 * @method Filial              setTelefono2()     Sets the current record's "telefono2" value
 * @method Filial              setTelefono3()     Sets the current record's "telefono3" value
 * @method Filial              setDescripcion()   Sets the current record's "descripcion" value
 * @method Filial              setCodigo()        Sets the current record's "codigo" value
 * @method Filial              setGeoubicacion()  Sets the current record's "geoubicacion" value
 * @method Filial              setGeoubicacion2() Sets the current record's "geoubicacion2" value
 * @method Filial              setPlanta()        Sets the current record's "Planta" collection
 * @method Filial              setEmpleados()     Sets the current record's "Empleados" collection
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFilial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('filial');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('direccion', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('telefono', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('telefono2', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('telefono3', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('descripcion', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('codigo', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('geoubicacion', 'string', 600, array(
             'type' => 'string',
             'length' => 600,
             ));
        $this->hasColumn('geoubicacion2', 'string', 600, array(
             'type' => 'string',
             'length' => 600,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Planta', array(
             'local' => 'id',
             'foreign' => 'filial_id'));

        $this->hasMany('Empleado as Empleados', array(
             'local' => 'id',
             'foreign' => 'centro_salud_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}