<?php

/**
 * BaseServicioMantenimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $internado_id
 * @property string $solicitante
 * @property string $sector
 * @property date $fecha_solicitante
 * @property string $objeto_reparado
 * @property string $caracteristicas
 * @property string $trabajo_solicitado
 * @property string $conformidad
 * @property string $reparado_por
 * @property integer $importe
 * @property date $importe_fecha
 * @property Internado $Internado
 * 
 * @method integer               getInternadoId()        Returns the current record's "internado_id" value
 * @method string                getSolicitante()        Returns the current record's "solicitante" value
 * @method string                getSector()             Returns the current record's "sector" value
 * @method date                  getFechaSolicitante()   Returns the current record's "fecha_solicitante" value
 * @method string                getObjetoReparado()     Returns the current record's "objeto_reparado" value
 * @method string                getCaracteristicas()    Returns the current record's "caracteristicas" value
 * @method string                getTrabajoSolicitado()  Returns the current record's "trabajo_solicitado" value
 * @method string                getConformidad()        Returns the current record's "conformidad" value
 * @method string                getReparadoPor()        Returns the current record's "reparado_por" value
 * @method integer               getImporte()            Returns the current record's "importe" value
 * @method date                  getImporteFecha()       Returns the current record's "importe_fecha" value
 * @method Internado             getInternado()          Returns the current record's "Internado" value
 * @method ServicioMantenimiento setInternadoId()        Sets the current record's "internado_id" value
 * @method ServicioMantenimiento setSolicitante()        Sets the current record's "solicitante" value
 * @method ServicioMantenimiento setSector()             Sets the current record's "sector" value
 * @method ServicioMantenimiento setFechaSolicitante()   Sets the current record's "fecha_solicitante" value
 * @method ServicioMantenimiento setObjetoReparado()     Sets the current record's "objeto_reparado" value
 * @method ServicioMantenimiento setCaracteristicas()    Sets the current record's "caracteristicas" value
 * @method ServicioMantenimiento setTrabajoSolicitado()  Sets the current record's "trabajo_solicitado" value
 * @method ServicioMantenimiento setConformidad()        Sets the current record's "conformidad" value
 * @method ServicioMantenimiento setReparadoPor()        Sets the current record's "reparado_por" value
 * @method ServicioMantenimiento setImporte()            Sets the current record's "importe" value
 * @method ServicioMantenimiento setImporteFecha()       Sets the current record's "importe_fecha" value
 * @method ServicioMantenimiento setInternado()          Sets the current record's "Internado" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServicioMantenimiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servicio_mantenimiento');
        $this->hasColumn('internado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('solicitante', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('sector', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('fecha_solicitante', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('objeto_reparado', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('caracteristicas', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('trabajo_solicitado', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('conformidad', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('reparado_por', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('importe', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('importe_fecha', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Internado', array(
             'local' => 'internado_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}