<?php

/**
 * BaseProgramacionCirugias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $file_internacion_id
 * @property integer $medico_id
 * @property date $operacion_fecha
 * @property time $operacion_hora
 * @property string $diagnostico_preoperatorio
 * @property string $tratamiento_quirurgico
 * @property string $anestesia
 * @property string $otros
 * @property string $examenes_auxiliares
 * @property date $fecha
 * @property integer $enfermera_id
 * @property string $enviado
 * @property string $recibido
 * @property FileInternacion $FileInternacion
 * 
 * @method integer              getId()                        Returns the current record's "id" value
 * @method integer              getFileInternacionId()         Returns the current record's "file_internacion_id" value
 * @method integer              getMedicoId()                  Returns the current record's "medico_id" value
 * @method date                 getOperacionFecha()            Returns the current record's "operacion_fecha" value
 * @method time                 getOperacionHora()             Returns the current record's "operacion_hora" value
 * @method string               getDiagnosticoPreoperatorio()  Returns the current record's "diagnostico_preoperatorio" value
 * @method string               getTratamientoQuirurgico()     Returns the current record's "tratamiento_quirurgico" value
 * @method string               getAnestesia()                 Returns the current record's "anestesia" value
 * @method string               getOtros()                     Returns the current record's "otros" value
 * @method string               getExamenesAuxiliares()        Returns the current record's "examenes_auxiliares" value
 * @method date                 getFecha()                     Returns the current record's "fecha" value
 * @method integer              getEnfermeraId()               Returns the current record's "enfermera_id" value
 * @method string               getEnviado()                   Returns the current record's "enviado" value
 * @method string               getRecibido()                  Returns the current record's "recibido" value
 * @method FileInternacion      getFileInternacion()           Returns the current record's "FileInternacion" value
 * @method ProgramacionCirugias setId()                        Sets the current record's "id" value
 * @method ProgramacionCirugias setFileInternacionId()         Sets the current record's "file_internacion_id" value
 * @method ProgramacionCirugias setMedicoId()                  Sets the current record's "medico_id" value
 * @method ProgramacionCirugias setOperacionFecha()            Sets the current record's "operacion_fecha" value
 * @method ProgramacionCirugias setOperacionHora()             Sets the current record's "operacion_hora" value
 * @method ProgramacionCirugias setDiagnosticoPreoperatorio()  Sets the current record's "diagnostico_preoperatorio" value
 * @method ProgramacionCirugias setTratamientoQuirurgico()     Sets the current record's "tratamiento_quirurgico" value
 * @method ProgramacionCirugias setAnestesia()                 Sets the current record's "anestesia" value
 * @method ProgramacionCirugias setOtros()                     Sets the current record's "otros" value
 * @method ProgramacionCirugias setExamenesAuxiliares()        Sets the current record's "examenes_auxiliares" value
 * @method ProgramacionCirugias setFecha()                     Sets the current record's "fecha" value
 * @method ProgramacionCirugias setEnfermeraId()               Sets the current record's "enfermera_id" value
 * @method ProgramacionCirugias setEnviado()                   Sets the current record's "enviado" value
 * @method ProgramacionCirugias setRecibido()                  Sets the current record's "recibido" value
 * @method ProgramacionCirugias setFileInternacion()           Sets the current record's "FileInternacion" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProgramacionCirugias extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('programacion_cirugias');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('file_internacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('medico_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('operacion_fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('operacion_hora', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('diagnostico_preoperatorio', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('tratamiento_quirurgico', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('anestesia', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('otros', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('examenes_auxiliares', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('enfermera_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('enviado', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('recibido', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FileInternacion', array(
             'local' => 'file_internacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}