<?php

/**
 * BaseEmpleado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $matricula
 * @property string $profesion
 * @property integer $centro_salud_id
 * @property string $nombre
 * @property string $apellido
 * @property string $cargo
 * @property Filial $Filial
 * 
 * @method string   getMatricula()       Returns the current record's "matricula" value
 * @method string   getProfesion()       Returns the current record's "profesion" value
 * @method integer  getCentroSaludId()   Returns the current record's "centro_salud_id" value
 * @method string   getNombre()          Returns the current record's "nombre" value
 * @method string   getApellido()        Returns the current record's "apellido" value
 * @method string   getCargo()           Returns the current record's "cargo" value
 * @method Filial   getFilial()          Returns the current record's "Filial" value
 * @method Empleado setMatricula()       Sets the current record's "matricula" value
 * @method Empleado setProfesion()       Sets the current record's "profesion" value
 * @method Empleado setCentroSaludId()   Sets the current record's "centro_salud_id" value
 * @method Empleado setNombre()          Sets the current record's "nombre" value
 * @method Empleado setApellido()        Sets the current record's "apellido" value
 * @method Empleado setCargo()           Sets the current record's "cargo" value
 * @method Empleado setFilial()          Sets the current record's "Filial" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpleado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('empleado');
        $this->hasColumn('matricula', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('profesion', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('centro_salud_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('apellido', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('cargo', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));


        $this->index('empleado_unique1', array(
             'type' => 'unique',
             'fields' => 'matricula',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Filial', array(
             'local' => 'centro_salud_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}