<?php

/**
 * BaseAdministracionMedicamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $internado_id
 * @property Internado $Internado
 * @property Doctrine_Collection $DetallesAdminMedicamento
 * 
 * @method integer                   getInternadoId()              Returns the current record's "internado_id" value
 * @method Internado                 getInternado()                Returns the current record's "Internado" value
 * @method Doctrine_Collection       getDetallesAdminMedicamento() Returns the current record's "DetallesAdminMedicamento" collection
 * @method AdministracionMedicamento setInternadoId()              Sets the current record's "internado_id" value
 * @method AdministracionMedicamento setInternado()                Sets the current record's "Internado" value
 * @method AdministracionMedicamento setDetallesAdminMedicamento() Sets the current record's "DetallesAdminMedicamento" collection
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdministracionMedicamento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('administracion_medicamento');
        $this->hasColumn('internado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Internado', array(
             'local' => 'internado_id',
             'foreign' => 'id'));

        $this->hasMany('DetalleAdminMedicamento as DetallesAdminMedicamento', array(
             'local' => 'id',
             'foreign' => 'administracion_medicamento_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}