<?php

/**
 * BaseDietaPaciente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $lista_dieta_id
 * @property integer $file_internacion_id
 * @property string $dieta
 * @property string $diagnostico
 * @property FileInternacion $FileInternacion
 * @property ListaDieta $ListaDieta
 * 
 * @method integer         getId()                  Returns the current record's "id" value
 * @method integer         getListaDietaId()        Returns the current record's "lista_dieta_id" value
 * @method integer         getFileInternacionId()   Returns the current record's "file_internacion_id" value
 * @method string          getDieta()               Returns the current record's "dieta" value
 * @method string          getDiagnostico()         Returns the current record's "diagnostico" value
 * @method FileInternacion getFileInternacion()     Returns the current record's "FileInternacion" value
 * @method ListaDieta      getListaDieta()          Returns the current record's "ListaDieta" value
 * @method DietaPaciente   setId()                  Sets the current record's "id" value
 * @method DietaPaciente   setListaDietaId()        Sets the current record's "lista_dieta_id" value
 * @method DietaPaciente   setFileInternacionId()   Sets the current record's "file_internacion_id" value
 * @method DietaPaciente   setDieta()               Sets the current record's "dieta" value
 * @method DietaPaciente   setDiagnostico()         Sets the current record's "diagnostico" value
 * @method DietaPaciente   setFileInternacion()     Sets the current record's "FileInternacion" value
 * @method DietaPaciente   setListaDieta()          Sets the current record's "ListaDieta" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDietaPaciente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dieta_paciente');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('lista_dieta_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('file_internacion_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dieta', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('diagnostico', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FileInternacion', array(
             'local' => 'file_internacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ListaDieta', array(
             'local' => 'lista_dieta_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}