<?php

/**
 * BaseNotasEvolucion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $file_internacion_id
 * @property integer $numero_hoja
 * @property FileInternacion $FileInternacion
 * @property Doctrine_Collection $DetalleEvolucion
 * 
 * @method integer             getFileInternacionId()   Returns the current record's "file_internacion_id" value
 * @method integer             getNumeroHoja()          Returns the current record's "numero_hoja" value
 * @method FileInternacion     getFileInternacion()     Returns the current record's "FileInternacion" value
 * @method Doctrine_Collection getDetalleEvolucion()    Returns the current record's "DetalleEvolucion" collection
 * @method NotasEvolucion      setFileInternacionId()   Sets the current record's "file_internacion_id" value
 * @method NotasEvolucion      setNumeroHoja()          Sets the current record's "numero_hoja" value
 * @method NotasEvolucion      setFileInternacion()     Sets the current record's "FileInternacion" value
 * @method NotasEvolucion      setDetalleEvolucion()    Sets the current record's "DetalleEvolucion" collection
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotasEvolucion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notas_evolucion');
        $this->hasColumn('file_internacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('numero_hoja', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FileInternacion', array(
             'local' => 'file_internacion_id',
             'foreign' => 'id'));

        $this->hasMany('DetalleEvolucion', array(
             'local' => 'id',
             'foreign' => 'notas_evolucion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}