<?php

/**
 * BaseAdministracionMedicamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $internado_id
 * @property integer $enfermera_id
 * @property string $medicamento_solucion
 * @property string $tipo
 * @property date $fecha
 * @property time $horario
 * @property Internado $Internado
 * 
 * @method integer                   getInternadoId()          Returns the current record's "internado_id" value
 * @method integer                   getEnfermeraId()          Returns the current record's "enfermera_id" value
 * @method string                    getMedicamentoSolucion()  Returns the current record's "medicamento_solucion" value
 * @method string                    getTipo()                 Returns the current record's "tipo" value
 * @method date                      getFecha()                Returns the current record's "fecha" value
 * @method time                      getHorario()              Returns the current record's "horario" value
 * @method Internado                 getInternado()            Returns the current record's "Internado" value
 * @method AdministracionMedicamento setInternadoId()          Sets the current record's "internado_id" value
 * @method AdministracionMedicamento setEnfermeraId()          Sets the current record's "enfermera_id" value
 * @method AdministracionMedicamento setMedicamentoSolucion()  Sets the current record's "medicamento_solucion" value
 * @method AdministracionMedicamento setTipo()                 Sets the current record's "tipo" value
 * @method AdministracionMedicamento setFecha()                Sets the current record's "fecha" value
 * @method AdministracionMedicamento setHorario()              Sets the current record's "horario" value
 * @method AdministracionMedicamento setInternado()            Sets the current record's "Internado" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdministracionMedicamento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('administracion_medicamento');
        $this->hasColumn('internado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('enfermera_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('medicamento_solucion', 'string', 400, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 400,
             ));
        $this->hasColumn('tipo', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('horario', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Internado', array(
             'local' => 'internado_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $anulablebehavior0 = new AnulableBehavior(array(
             'type' => 'string',
             'length' => 200,
             'name' => 'motivo_anulacion',
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($anulablebehavior0);
    }
}