<?php

/**
 * BaseSolicitudExamenLaboratorio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $file_internacion_id
 * @property integer $doctor_id
 * @property string $material_enviado
 * @property string $otros_examenes
 * @property string $diagnostico_presuntivo
 * @property integer $medico_id
 * @property string $lugar
 * @property date $fecha
 * @property FileInternacion $FileInternacion
 * @property Doctrine_Collection $SolicitudExamenLaboratorio
 * 
 * @method integer                    getId()                         Returns the current record's "id" value
 * @method integer                    getFileInternacionId()          Returns the current record's "file_internacion_id" value
 * @method integer                    getDoctorId()                   Returns the current record's "doctor_id" value
 * @method string                     getMaterialEnviado()            Returns the current record's "material_enviado" value
 * @method string                     getOtrosExamenes()              Returns the current record's "otros_examenes" value
 * @method string                     getDiagnosticoPresuntivo()      Returns the current record's "diagnostico_presuntivo" value
 * @method integer                    getMedicoId()                   Returns the current record's "medico_id" value
 * @method string                     getLugar()                      Returns the current record's "lugar" value
 * @method date                       getFecha()                      Returns the current record's "fecha" value
 * @method FileInternacion            getFileInternacion()            Returns the current record's "FileInternacion" value
 * @method Doctrine_Collection        getSolicitudExamenLaboratorio() Returns the current record's "SolicitudExamenLaboratorio" collection
 * @method SolicitudExamenLaboratorio setId()                         Sets the current record's "id" value
 * @method SolicitudExamenLaboratorio setFileInternacionId()          Sets the current record's "file_internacion_id" value
 * @method SolicitudExamenLaboratorio setDoctorId()                   Sets the current record's "doctor_id" value
 * @method SolicitudExamenLaboratorio setMaterialEnviado()            Sets the current record's "material_enviado" value
 * @method SolicitudExamenLaboratorio setOtrosExamenes()              Sets the current record's "otros_examenes" value
 * @method SolicitudExamenLaboratorio setDiagnosticoPresuntivo()      Sets the current record's "diagnostico_presuntivo" value
 * @method SolicitudExamenLaboratorio setMedicoId()                   Sets the current record's "medico_id" value
 * @method SolicitudExamenLaboratorio setLugar()                      Sets the current record's "lugar" value
 * @method SolicitudExamenLaboratorio setFecha()                      Sets the current record's "fecha" value
 * @method SolicitudExamenLaboratorio setFileInternacion()            Sets the current record's "FileInternacion" value
 * @method SolicitudExamenLaboratorio setSolicitudExamenLaboratorio() Sets the current record's "SolicitudExamenLaboratorio" collection
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSolicitudExamenLaboratorio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('solicitud_examen_laboratorio');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('file_internacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('doctor_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('material_enviado', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('otros_examenes', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('diagnostico_presuntivo', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('medico_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('lugar', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FileInternacion', array(
             'local' => 'file_internacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('DetalleSolicitudExamenLaboratorio as SolicitudExamenLaboratorio', array(
             'local' => 'id',
             'foreign' => 'solicitud_examen_laboratorio_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}