<?php

/**
 * BaseAtencion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Doctrine_Collection $SolicitudServicio
 * 
 * @method string              getNombre()            Returns the current record's "nombre" value
 * @method Doctrine_Collection getSolicitudServicio() Returns the current record's "SolicitudServicio" collection
 * @method Atencion            setNombre()            Sets the current record's "nombre" value
 * @method Atencion            setSolicitudServicio() Sets the current record's "SolicitudServicio" collection
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAtencion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('atencion');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SolicitudServicio', array(
             'local' => 'id',
             'foreign' => 'atencion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}