<?php

/**
 * BaseEspecialidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $activo
 * @property integer $cupos
 * @property integer $servicio_id
 * @property integer $filial_id
 * @property string $observacion
 * @property Doctrine_Collection $Medicos
 * 
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getActivo()      Returns the current record's "activo" value
 * @method integer             getCupos()       Returns the current record's "cupos" value
 * @method integer             getServicioId()  Returns the current record's "servicio_id" value
 * @method integer             getFilialId()    Returns the current record's "filial_id" value
 * @method string              getObservacion() Returns the current record's "observacion" value
 * @method Doctrine_Collection getMedicos()     Returns the current record's "Medicos" collection
 * @method Especialidad        setNombre()      Sets the current record's "nombre" value
 * @method Especialidad        setActivo()      Sets the current record's "activo" value
 * @method Especialidad        setCupos()       Sets the current record's "cupos" value
 * @method Especialidad        setServicioId()  Sets the current record's "servicio_id" value
 * @method Especialidad        setFilialId()    Sets the current record's "filial_id" value
 * @method Especialidad        setObservacion() Sets the current record's "observacion" value
 * @method Especialidad        setMedicos()     Sets the current record's "Medicos" collection
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEspecialidad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('especialidad');
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('activo', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 1,
             'length' => 1,
             ));
        $this->hasColumn('cupos', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('servicio_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('filial_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('observacion', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Medico as Medicos', array(
             'local' => 'id',
             'foreign' => 'especialidad_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}