<?php

/**
 * BaseAtencionEnfermeria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $internado_id
 * @property integer $enfermera_id
 * @property integer $medico_id
 * @property string $diagnostico_medico
 * @property timestamp $fecha_ingreso
 * @property string $acompano_por
 * @property string $estado
 * @property string $derivado_de
 * @property string $especificar_derivado
 * @property string $cuidador_principal
 * @property string $especificar_cuidador
 * @property integer $edad
 * @property integer $peso
 * @property integer $talla
 * @property string $sexo
 * @property string $temperatura
 * @property string $pulso
 * @property string $respiracion
 * @property string $presion_arterial
 * @property string $per_apariencia_gral_esc
 * @property string $per_apariencia_gral_val
 * @property string $per_habitos_esc
 * @property string $per_habitos_val
 * @property string $per_alergias_esc
 * @property string $per_alergias_val
 * @property string $per_inmunizaciones_esc
 * @property string $per_inmunizaciones_val
 * @property string $per_medicacion_actual_esc
 * @property string $per_medicacion_actual_val
 * @property string $motivo_ingreso
 * @property string $nutmet_higiene_esc
 * @property string $nutmet_higiene_val
 * @property string $nutmet_estado_nutricional_esc
 * @property string $nutmet_estado_nutricional_val
 * @property string $nutmet_protesis_dental_esc
 * @property string $nutmet_protesis_dental_val
 * @property string $nutmet_liquidos_electrolitos_esc
 * @property string $nutmet_liquidos_electrolitos_val
 * @property string $patelim_habito_intestinal_esc
 * @property string $patelim_habito_intestinal_val
 * @property string $patelim_habito_urinario_esc
 * @property string $patelim_habito_urinario_val
 * @property string $acteje_valoracion_cardiopulmonar_esc
 * @property string $acteje_valoracion_cardiopulmonar_val
 * @property string $acteje_capacidad_motora_esc
 * @property string $acteje_capacidad_motora_val
 * @property string $acteje_act_diversion_esc
 * @property string $acteje_act_diversion_val
 * @property string $acteje_deficit_autocuidado_esc
 * @property string $acteje_deficit_autocuidado_val
 * @property string $acteje_crecim_desarrollo_esc
 * @property string $acteje_crecim_desarrollo_val
 * @property string $des_habito_descanso_esc
 * @property string $des_habito_descanso_val
 * @property string $des_transtorno_sueno_esc
 * @property string $des_transtorno_sueno_val
 * @property string $cogper_alter_sensoriales_esc
 * @property string $cogper_alter_sensoriales_val
 * @property string $cogper_nivel_conciencia_esc
 * @property string $cogper_nivel_conciencia_val
 * @property string $cogper_alteracion_promentales_esc
 * @property string $cogper_alteracion_promentales_val
 * @property string $auto_reaccion_emocional_esc
 * @property string $auto_reaccion_emocional_val
 * @property string $relrol_relacion_interpersonal_esc
 * @property string $relrol_relacion_interpersonal_val
 * @property string $relrol_conducta_familia_esc
 * @property string $relrol_conducta_familia_val
 * @property string $relrol_cambio_personalfamiliar_esc
 * @property string $relrol_cambio_personalfamiliar_val
 * @property string $repsex_alteracion_sisreproductivo_esc
 * @property string $repsex_alteracion_sisreproductivo_val
 * @property string $capstr_relpaciente_enfermedad_esc
 * @property string $capstr_relpaciente_enfermedad_val
 * @property string $capstr_relfamilia_enfermedad_esc
 * @property string $capstr_relfamilia_enfermedad_val
 * @property string $creencia_religiosa
 * @property string $diagnostico_enfermera
 * @property Internado $Internado
 * @property Medico $Medico
 * 
 * @method integer            getInternadoId()                           Returns the current record's "internado_id" value
 * @method integer            getEnfermeraId()                           Returns the current record's "enfermera_id" value
 * @method integer            getMedicoId()                              Returns the current record's "medico_id" value
 * @method string             getDiagnosticoMedico()                     Returns the current record's "diagnostico_medico" value
 * @method timestamp          getFechaIngreso()                          Returns the current record's "fecha_ingreso" value
 * @method string             getAcompanoPor()                           Returns the current record's "acompano_por" value
 * @method string             getEstado()                                Returns the current record's "estado" value
 * @method string             getDerivadoDe()                            Returns the current record's "derivado_de" value
 * @method string             getEspecificarDerivado()                   Returns the current record's "especificar_derivado" value
 * @method string             getCuidadorPrincipal()                     Returns the current record's "cuidador_principal" value
 * @method string             getEspecificarCuidador()                   Returns the current record's "especificar_cuidador" value
 * @method integer            getEdad()                                  Returns the current record's "edad" value
 * @method integer            getPeso()                                  Returns the current record's "peso" value
 * @method integer            getTalla()                                 Returns the current record's "talla" value
 * @method string             getSexo()                                  Returns the current record's "sexo" value
 * @method string             getTemperatura()                           Returns the current record's "temperatura" value
 * @method string             getPulso()                                 Returns the current record's "pulso" value
 * @method string             getRespiracion()                           Returns the current record's "respiracion" value
 * @method string             getPresionArterial()                       Returns the current record's "presion_arterial" value
 * @method string             getPerAparienciaGralEsc()                  Returns the current record's "per_apariencia_gral_esc" value
 * @method string             getPerAparienciaGralVal()                  Returns the current record's "per_apariencia_gral_val" value
 * @method string             getPerHabitosEsc()                         Returns the current record's "per_habitos_esc" value
 * @method string             getPerHabitosVal()                         Returns the current record's "per_habitos_val" value
 * @method string             getPerAlergiasEsc()                        Returns the current record's "per_alergias_esc" value
 * @method string             getPerAlergiasVal()                        Returns the current record's "per_alergias_val" value
 * @method string             getPerInmunizacionesEsc()                  Returns the current record's "per_inmunizaciones_esc" value
 * @method string             getPerInmunizacionesVal()                  Returns the current record's "per_inmunizaciones_val" value
 * @method string             getPerMedicacionActualEsc()                Returns the current record's "per_medicacion_actual_esc" value
 * @method string             getPerMedicacionActualVal()                Returns the current record's "per_medicacion_actual_val" value
 * @method string             getMotivoIngreso()                         Returns the current record's "motivo_ingreso" value
 * @method string             getNutmetHigieneEsc()                      Returns the current record's "nutmet_higiene_esc" value
 * @method string             getNutmetHigieneVal()                      Returns the current record's "nutmet_higiene_val" value
 * @method string             getNutmetEstadoNutricionalEsc()            Returns the current record's "nutmet_estado_nutricional_esc" value
 * @method string             getNutmetEstadoNutricionalVal()            Returns the current record's "nutmet_estado_nutricional_val" value
 * @method string             getNutmetProtesisDentalEsc()               Returns the current record's "nutmet_protesis_dental_esc" value
 * @method string             getNutmetProtesisDentalVal()               Returns the current record's "nutmet_protesis_dental_val" value
 * @method string             getNutmetLiquidosElectrolitosEsc()         Returns the current record's "nutmet_liquidos_electrolitos_esc" value
 * @method string             getNutmetLiquidosElectrolitosVal()         Returns the current record's "nutmet_liquidos_electrolitos_val" value
 * @method string             getPatelimHabitoIntestinalEsc()            Returns the current record's "patelim_habito_intestinal_esc" value
 * @method string             getPatelimHabitoIntestinalVal()            Returns the current record's "patelim_habito_intestinal_val" value
 * @method string             getPatelimHabitoUrinarioEsc()              Returns the current record's "patelim_habito_urinario_esc" value
 * @method string             getPatelimHabitoUrinarioVal()              Returns the current record's "patelim_habito_urinario_val" value
 * @method string             getActejeValoracionCardiopulmonarEsc()     Returns the current record's "acteje_valoracion_cardiopulmonar_esc" value
 * @method string             getActejeValoracionCardiopulmonarVal()     Returns the current record's "acteje_valoracion_cardiopulmonar_val" value
 * @method string             getActejeCapacidadMotoraEsc()              Returns the current record's "acteje_capacidad_motora_esc" value
 * @method string             getActejeCapacidadMotoraVal()              Returns the current record's "acteje_capacidad_motora_val" value
 * @method string             getActejeActDiversionEsc()                 Returns the current record's "acteje_act_diversion_esc" value
 * @method string             getActejeActDiversionVal()                 Returns the current record's "acteje_act_diversion_val" value
 * @method string             getActejeDeficitAutocuidadoEsc()           Returns the current record's "acteje_deficit_autocuidado_esc" value
 * @method string             getActejeDeficitAutocuidadoVal()           Returns the current record's "acteje_deficit_autocuidado_val" value
 * @method string             getActejeCrecimDesarrolloEsc()             Returns the current record's "acteje_crecim_desarrollo_esc" value
 * @method string             getActejeCrecimDesarrolloVal()             Returns the current record's "acteje_crecim_desarrollo_val" value
 * @method string             getDesHabitoDescansoEsc()                  Returns the current record's "des_habito_descanso_esc" value
 * @method string             getDesHabitoDescansoVal()                  Returns the current record's "des_habito_descanso_val" value
 * @method string             getDesTranstornoSuenoEsc()                 Returns the current record's "des_transtorno_sueno_esc" value
 * @method string             getDesTranstornoSuenoVal()                 Returns the current record's "des_transtorno_sueno_val" value
 * @method string             getCogperAlterSensorialesEsc()             Returns the current record's "cogper_alter_sensoriales_esc" value
 * @method string             getCogperAlterSensorialesVal()             Returns the current record's "cogper_alter_sensoriales_val" value
 * @method string             getCogperNivelConcienciaEsc()              Returns the current record's "cogper_nivel_conciencia_esc" value
 * @method string             getCogperNivelConcienciaVal()              Returns the current record's "cogper_nivel_conciencia_val" value
 * @method string             getCogperAlteracionPromentalesEsc()        Returns the current record's "cogper_alteracion_promentales_esc" value
 * @method string             getCogperAlteracionPromentalesVal()        Returns the current record's "cogper_alteracion_promentales_val" value
 * @method string             getAutoReaccionEmocionalEsc()              Returns the current record's "auto_reaccion_emocional_esc" value
 * @method string             getAutoReaccionEmocionalVal()              Returns the current record's "auto_reaccion_emocional_val" value
 * @method string             getRelrolRelacionInterpersonalEsc()        Returns the current record's "relrol_relacion_interpersonal_esc" value
 * @method string             getRelrolRelacionInterpersonalVal()        Returns the current record's "relrol_relacion_interpersonal_val" value
 * @method string             getRelrolConductaFamiliaEsc()              Returns the current record's "relrol_conducta_familia_esc" value
 * @method string             getRelrolConductaFamiliaVal()              Returns the current record's "relrol_conducta_familia_val" value
 * @method string             getRelrolCambioPersonalfamiliarEsc()       Returns the current record's "relrol_cambio_personalfamiliar_esc" value
 * @method string             getRelrolCambioPersonalfamiliarVal()       Returns the current record's "relrol_cambio_personalfamiliar_val" value
 * @method string             getRepsexAlteracionSisreproductivoEsc()    Returns the current record's "repsex_alteracion_sisreproductivo_esc" value
 * @method string             getRepsexAlteracionSisreproductivoVal()    Returns the current record's "repsex_alteracion_sisreproductivo_val" value
 * @method string             getCapstrRelpacienteEnfermedadEsc()        Returns the current record's "capstr_relpaciente_enfermedad_esc" value
 * @method string             getCapstrRelpacienteEnfermedadVal()        Returns the current record's "capstr_relpaciente_enfermedad_val" value
 * @method string             getCapstrRelfamiliaEnfermedadEsc()         Returns the current record's "capstr_relfamilia_enfermedad_esc" value
 * @method string             getCapstrRelfamiliaEnfermedadVal()         Returns the current record's "capstr_relfamilia_enfermedad_val" value
 * @method string             getCreenciaReligiosa()                     Returns the current record's "creencia_religiosa" value
 * @method string             getDiagnosticoEnfermera()                  Returns the current record's "diagnostico_enfermera" value
 * @method Internado          getInternado()                             Returns the current record's "Internado" value
 * @method Medico             getMedico()                                Returns the current record's "Medico" value
 * @method AtencionEnfermeria setInternadoId()                           Sets the current record's "internado_id" value
 * @method AtencionEnfermeria setEnfermeraId()                           Sets the current record's "enfermera_id" value
 * @method AtencionEnfermeria setMedicoId()                              Sets the current record's "medico_id" value
 * @method AtencionEnfermeria setDiagnosticoMedico()                     Sets the current record's "diagnostico_medico" value
 * @method AtencionEnfermeria setFechaIngreso()                          Sets the current record's "fecha_ingreso" value
 * @method AtencionEnfermeria setAcompanoPor()                           Sets the current record's "acompano_por" value
 * @method AtencionEnfermeria setEstado()                                Sets the current record's "estado" value
 * @method AtencionEnfermeria setDerivadoDe()                            Sets the current record's "derivado_de" value
 * @method AtencionEnfermeria setEspecificarDerivado()                   Sets the current record's "especificar_derivado" value
 * @method AtencionEnfermeria setCuidadorPrincipal()                     Sets the current record's "cuidador_principal" value
 * @method AtencionEnfermeria setEspecificarCuidador()                   Sets the current record's "especificar_cuidador" value
 * @method AtencionEnfermeria setEdad()                                  Sets the current record's "edad" value
 * @method AtencionEnfermeria setPeso()                                  Sets the current record's "peso" value
 * @method AtencionEnfermeria setTalla()                                 Sets the current record's "talla" value
 * @method AtencionEnfermeria setSexo()                                  Sets the current record's "sexo" value
 * @method AtencionEnfermeria setTemperatura()                           Sets the current record's "temperatura" value
 * @method AtencionEnfermeria setPulso()                                 Sets the current record's "pulso" value
 * @method AtencionEnfermeria setRespiracion()                           Sets the current record's "respiracion" value
 * @method AtencionEnfermeria setPresionArterial()                       Sets the current record's "presion_arterial" value
 * @method AtencionEnfermeria setPerAparienciaGralEsc()                  Sets the current record's "per_apariencia_gral_esc" value
 * @method AtencionEnfermeria setPerAparienciaGralVal()                  Sets the current record's "per_apariencia_gral_val" value
 * @method AtencionEnfermeria setPerHabitosEsc()                         Sets the current record's "per_habitos_esc" value
 * @method AtencionEnfermeria setPerHabitosVal()                         Sets the current record's "per_habitos_val" value
 * @method AtencionEnfermeria setPerAlergiasEsc()                        Sets the current record's "per_alergias_esc" value
 * @method AtencionEnfermeria setPerAlergiasVal()                        Sets the current record's "per_alergias_val" value
 * @method AtencionEnfermeria setPerInmunizacionesEsc()                  Sets the current record's "per_inmunizaciones_esc" value
 * @method AtencionEnfermeria setPerInmunizacionesVal()                  Sets the current record's "per_inmunizaciones_val" value
 * @method AtencionEnfermeria setPerMedicacionActualEsc()                Sets the current record's "per_medicacion_actual_esc" value
 * @method AtencionEnfermeria setPerMedicacionActualVal()                Sets the current record's "per_medicacion_actual_val" value
 * @method AtencionEnfermeria setMotivoIngreso()                         Sets the current record's "motivo_ingreso" value
 * @method AtencionEnfermeria setNutmetHigieneEsc()                      Sets the current record's "nutmet_higiene_esc" value
 * @method AtencionEnfermeria setNutmetHigieneVal()                      Sets the current record's "nutmet_higiene_val" value
 * @method AtencionEnfermeria setNutmetEstadoNutricionalEsc()            Sets the current record's "nutmet_estado_nutricional_esc" value
 * @method AtencionEnfermeria setNutmetEstadoNutricionalVal()            Sets the current record's "nutmet_estado_nutricional_val" value
 * @method AtencionEnfermeria setNutmetProtesisDentalEsc()               Sets the current record's "nutmet_protesis_dental_esc" value
 * @method AtencionEnfermeria setNutmetProtesisDentalVal()               Sets the current record's "nutmet_protesis_dental_val" value
 * @method AtencionEnfermeria setNutmetLiquidosElectrolitosEsc()         Sets the current record's "nutmet_liquidos_electrolitos_esc" value
 * @method AtencionEnfermeria setNutmetLiquidosElectrolitosVal()         Sets the current record's "nutmet_liquidos_electrolitos_val" value
 * @method AtencionEnfermeria setPatelimHabitoIntestinalEsc()            Sets the current record's "patelim_habito_intestinal_esc" value
 * @method AtencionEnfermeria setPatelimHabitoIntestinalVal()            Sets the current record's "patelim_habito_intestinal_val" value
 * @method AtencionEnfermeria setPatelimHabitoUrinarioEsc()              Sets the current record's "patelim_habito_urinario_esc" value
 * @method AtencionEnfermeria setPatelimHabitoUrinarioVal()              Sets the current record's "patelim_habito_urinario_val" value
 * @method AtencionEnfermeria setActejeValoracionCardiopulmonarEsc()     Sets the current record's "acteje_valoracion_cardiopulmonar_esc" value
 * @method AtencionEnfermeria setActejeValoracionCardiopulmonarVal()     Sets the current record's "acteje_valoracion_cardiopulmonar_val" value
 * @method AtencionEnfermeria setActejeCapacidadMotoraEsc()              Sets the current record's "acteje_capacidad_motora_esc" value
 * @method AtencionEnfermeria setActejeCapacidadMotoraVal()              Sets the current record's "acteje_capacidad_motora_val" value
 * @method AtencionEnfermeria setActejeActDiversionEsc()                 Sets the current record's "acteje_act_diversion_esc" value
 * @method AtencionEnfermeria setActejeActDiversionVal()                 Sets the current record's "acteje_act_diversion_val" value
 * @method AtencionEnfermeria setActejeDeficitAutocuidadoEsc()           Sets the current record's "acteje_deficit_autocuidado_esc" value
 * @method AtencionEnfermeria setActejeDeficitAutocuidadoVal()           Sets the current record's "acteje_deficit_autocuidado_val" value
 * @method AtencionEnfermeria setActejeCrecimDesarrolloEsc()             Sets the current record's "acteje_crecim_desarrollo_esc" value
 * @method AtencionEnfermeria setActejeCrecimDesarrolloVal()             Sets the current record's "acteje_crecim_desarrollo_val" value
 * @method AtencionEnfermeria setDesHabitoDescansoEsc()                  Sets the current record's "des_habito_descanso_esc" value
 * @method AtencionEnfermeria setDesHabitoDescansoVal()                  Sets the current record's "des_habito_descanso_val" value
 * @method AtencionEnfermeria setDesTranstornoSuenoEsc()                 Sets the current record's "des_transtorno_sueno_esc" value
 * @method AtencionEnfermeria setDesTranstornoSuenoVal()                 Sets the current record's "des_transtorno_sueno_val" value
 * @method AtencionEnfermeria setCogperAlterSensorialesEsc()             Sets the current record's "cogper_alter_sensoriales_esc" value
 * @method AtencionEnfermeria setCogperAlterSensorialesVal()             Sets the current record's "cogper_alter_sensoriales_val" value
 * @method AtencionEnfermeria setCogperNivelConcienciaEsc()              Sets the current record's "cogper_nivel_conciencia_esc" value
 * @method AtencionEnfermeria setCogperNivelConcienciaVal()              Sets the current record's "cogper_nivel_conciencia_val" value
 * @method AtencionEnfermeria setCogperAlteracionPromentalesEsc()        Sets the current record's "cogper_alteracion_promentales_esc" value
 * @method AtencionEnfermeria setCogperAlteracionPromentalesVal()        Sets the current record's "cogper_alteracion_promentales_val" value
 * @method AtencionEnfermeria setAutoReaccionEmocionalEsc()              Sets the current record's "auto_reaccion_emocional_esc" value
 * @method AtencionEnfermeria setAutoReaccionEmocionalVal()              Sets the current record's "auto_reaccion_emocional_val" value
 * @method AtencionEnfermeria setRelrolRelacionInterpersonalEsc()        Sets the current record's "relrol_relacion_interpersonal_esc" value
 * @method AtencionEnfermeria setRelrolRelacionInterpersonalVal()        Sets the current record's "relrol_relacion_interpersonal_val" value
 * @method AtencionEnfermeria setRelrolConductaFamiliaEsc()              Sets the current record's "relrol_conducta_familia_esc" value
 * @method AtencionEnfermeria setRelrolConductaFamiliaVal()              Sets the current record's "relrol_conducta_familia_val" value
 * @method AtencionEnfermeria setRelrolCambioPersonalfamiliarEsc()       Sets the current record's "relrol_cambio_personalfamiliar_esc" value
 * @method AtencionEnfermeria setRelrolCambioPersonalfamiliarVal()       Sets the current record's "relrol_cambio_personalfamiliar_val" value
 * @method AtencionEnfermeria setRepsexAlteracionSisreproductivoEsc()    Sets the current record's "repsex_alteracion_sisreproductivo_esc" value
 * @method AtencionEnfermeria setRepsexAlteracionSisreproductivoVal()    Sets the current record's "repsex_alteracion_sisreproductivo_val" value
 * @method AtencionEnfermeria setCapstrRelpacienteEnfermedadEsc()        Sets the current record's "capstr_relpaciente_enfermedad_esc" value
 * @method AtencionEnfermeria setCapstrRelpacienteEnfermedadVal()        Sets the current record's "capstr_relpaciente_enfermedad_val" value
 * @method AtencionEnfermeria setCapstrRelfamiliaEnfermedadEsc()         Sets the current record's "capstr_relfamilia_enfermedad_esc" value
 * @method AtencionEnfermeria setCapstrRelfamiliaEnfermedadVal()         Sets the current record's "capstr_relfamilia_enfermedad_val" value
 * @method AtencionEnfermeria setCreenciaReligiosa()                     Sets the current record's "creencia_religiosa" value
 * @method AtencionEnfermeria setDiagnosticoEnfermera()                  Sets the current record's "diagnostico_enfermera" value
 * @method AtencionEnfermeria setInternado()                             Sets the current record's "Internado" value
 * @method AtencionEnfermeria setMedico()                                Sets the current record's "Medico" value
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAtencionEnfermeria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('atencion_enfermeria');
        $this->hasColumn('internado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('enfermera_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('medico_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('diagnostico_medico', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('fecha_ingreso', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('acompano_por', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('estado', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('derivado_de', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('especificar_derivado', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('cuidador_principal', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 15,
             ));
        $this->hasColumn('especificar_cuidador', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('edad', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('peso', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('talla', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sexo', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('temperatura', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('pulso', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('respiracion', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('presion_arterial', 'string', 25, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('per_apariencia_gral_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('per_apariencia_gral_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('per_habitos_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('per_habitos_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('per_alergias_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('per_alergias_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('per_inmunizaciones_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('per_inmunizaciones_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('per_medicacion_actual_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('per_medicacion_actual_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('motivo_ingreso', 'string', 800, array(
             'type' => 'string',
             'length' => 800,
             ));
        $this->hasColumn('nutmet_higiene_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('nutmet_higiene_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('nutmet_estado_nutricional_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('nutmet_estado_nutricional_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('nutmet_protesis_dental_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('nutmet_protesis_dental_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('nutmet_liquidos_electrolitos_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('nutmet_liquidos_electrolitos_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('patelim_habito_intestinal_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('patelim_habito_intestinal_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('patelim_habito_urinario_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('patelim_habito_urinario_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('acteje_valoracion_cardiopulmonar_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('acteje_valoracion_cardiopulmonar_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('acteje_capacidad_motora_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('acteje_capacidad_motora_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('acteje_act_diversion_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('acteje_act_diversion_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('acteje_deficit_autocuidado_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('acteje_deficit_autocuidado_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('acteje_crecim_desarrollo_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('acteje_crecim_desarrollo_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('des_habito_descanso_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('des_habito_descanso_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('des_transtorno_sueno_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('des_transtorno_sueno_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('cogper_alter_sensoriales_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('cogper_alter_sensoriales_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('cogper_nivel_conciencia_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('cogper_nivel_conciencia_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('cogper_alteracion_promentales_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('cogper_alteracion_promentales_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('auto_reaccion_emocional_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('auto_reaccion_emocional_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('relrol_relacion_interpersonal_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('relrol_relacion_interpersonal_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('relrol_conducta_familia_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('relrol_conducta_familia_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('relrol_cambio_personalfamiliar_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('relrol_cambio_personalfamiliar_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('repsex_alteracion_sisreproductivo_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('repsex_alteracion_sisreproductivo_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('capstr_relpaciente_enfermedad_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('capstr_relpaciente_enfermedad_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('capstr_relfamilia_enfermedad_esc', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('capstr_relfamilia_enfermedad_val', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('creencia_religiosa', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('diagnostico_enfermera', 'string', 2500, array(
             'type' => 'string',
             'length' => 2500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Internado', array(
             'local' => 'internado_id',
             'foreign' => 'id'));

        $this->hasOne('Medico', array(
             'local' => 'medico_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $anulablebehavior0 = new AnulableBehavior(array(
             'type' => 'string',
             'length' => 200,
             'name' => 'motivo_anulacion',
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($anulablebehavior0);
    }
}