generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    dojo_forajax_component_id: main-container-tab4    

    config:
      fields:
        password_again: {label: "Repetir password"}
        username:       {label: "Usuario"}
        email_address:  {label: "Correo electronico"}
        is_active:      {label: "Esta activo"}
        is_super_admin: {label: "Es super usuario"}
        groups_list:    {label: "Lista de grupos"}
        created_at:     {label: "Creado en"}
        last_login:     {label: "Ultimo ingreso"}
      list:
        title:   Listado de Usuarios
        display: [username, nombre_completo, email_address, is_active, is_super_admin, created_at, last_login]         
        batch_actions: {}
      filter:
        display: [username]
      form:
        class: sfGuardUserAdminForm
        display:
          "Usuario":           [ _form_listado_empleado, email_address, username, password, password_again]
          "Permisos y grupos": [ is_active, is_super_admin, groups_list ]
        actions:
          _delete:  ~
          _list:    ~
          _save:    ~
      edit:
        title: Edición de Usuario "%%username%%"

      new:
        title: Nuevo Usuario