generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JuntaMedica
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          junta_medica
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  ~
      list:    
        title: Juntas Medicas
        display: [fecha_junta, medico_solicitante, diagnostico_establecido, conclusiones]
        object_actions:  
          _edit:        { credentials: [noHistory] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [siHistory] }
          _delete:      { credentials: [noHistory] }
        actions: {}
        batch_actions: {}
      filter:  
        display: [fecha_junta, medico_solicitante]
      form:            
        actions:
          _list: ~
          _save: { credentials: [noHistory] }
      edit:    
        title: Editar Junta Médica        
        display:
          Datos de la Junta Médica:       [fecha_junta, medico_solicitante, servicio, especialidades, diagnostico_establecido, relacion_junta, conclusiones, tac, contraste]
          Lista de Médicos Participantes: [_medicos_participantes]
          Adicionar Médico Participante:  [medico]
      edit:    
        title: Editar Junta Médica
        actions:
          _save: ~
      new:     
        title: Nueva Junta Médica
        display:
          Datos de la Junta Médica:      [fecha_junta, medico_solicitante, servicio, especialidades, diagnostico_establecido, conclusiones, tac, contraste]
          Adicionar Médico Participante: [medico]    
        actions:
          _list: ~
          _save: ~
