generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JuntaMedica
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          junta_medica
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id
    sfGuard_check_created_by: user_id

    config:
      actions: ~
      fields:  
        medico_id:     {label: Medico Solicitante}
        nombre_medico: {label: Medico Solicitante}
        creator:       {label: Responsable}
        fecha_junta:   {date_format: 'dd/MM/yyyy hh:mm' }
      list:    
        title: Juntas Medicas
        display: [fecha_junta, nombre_medico, diagnostico_establecido, conclusiones, creator]
        object_actions:  
          _edit:        { credentials: [noAlta, crear, medico] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [[enfermera, ver_todo_datos], alta] }
          imprimir:     {label: Imprimir, action: exportPdf, params: { onclick: "var w=window.open(this.href,'popupWindow','width=900,height=700,left=320,top=100,scrollbars=yes,menubar=no,resizable=no');w.focus();return false;" } }
          _delete:      { credentials: [noAlta, crear, medico] }
        actions: {}
        batch_actions: {}
      filter:  
        display: [fecha_junta, medico_id]
      form:            
        actions:
#          _delete: { credentials: [noAlta, crear, medico] }
          _list:   ~
          _save:   { credentials: [noAlta, crear, medico] }
      edit:    
        title: Editar Junta Médica        
        display:
          Datos de la Junta Médica:       [fecha_junta, medico_id, servicio, especialidades, diagnostico_establecido, relacion_junta, conclusiones, tac, contraste]
          Lista de Médicos Participantes: [_medicos_participantes]
          Adicionar Médico Participante:  [medico]        
      new:     
        title: Nueva Junta Médica
        display:
          Datos de la Junta Médica:      [fecha_junta, medico_id, servicio, especialidades, diagnostico_establecido, relacion_junta, conclusiones, tac, contraste]
          Adicionar Médico Participante: [medico] 
