generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JuntaMedica
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          junta_medica
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  ~
      list:    
        title: Juntas Medicas
        display: [fecha_junta, medico_solicitante, diagnostico_establecido, conclusiones]
        actions: {}
        batch_actions: {}
      filter:  
        display: [fecha_junta, medico_solicitante]
      form:    
        display:
          Datos de la Junta Médica: [fecha_junta, medico_solicitante, servicio, especialidades, diagnostico_establecido, conclusiones, tac, contraste]
          Médicos Participantes:    [medico]
      edit:    
        title: Editar Junta Médica
        actions:
          _save: ~
      new:     
        title: Nueva Junta Médica
        actions:
          _save: ~
          _save_and_add: ~