generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JuntaMedica
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          junta_medica
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id
#    sfGuard_check_created_by: user_id

    config:
      actions: ~
      fields:  
        creator:     {label: Responsable}
        fecha_junta: {date_format: 'dd/MM/yyyy hh:mm' }
      list:    
        title: Juntas Medicas
        display: [fecha_junta, medico_solicitante, diagnostico_establecido, conclusiones, creator]
        object_actions:  
          _edit:        { credentials: [noAlta] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [Alta] }
          _delete:      { credentials: [noAlta] }
        actions: {}
        batch_actions: {}
      filter:  
        display: [fecha_junta, medico_solicitante]
      form:            
        actions:
          _delete: { credentials: [noAlta] }
          _list:   ~
          _save:   { credentials: [noAlta] }
      edit:    
        title: Editar Junta Médica        
        display:
          Datos de la Junta Médica:       [fecha_junta, medico_solicitante, servicio, especialidades, diagnostico_establecido, relacion_junta, conclusiones, tac, contraste]
          Lista de Médicos Participantes: [_medicos_participantes]
          Adicionar Médico Participante:  [medico]        
      new:     
        title: Nueva Junta Médica
        display:
          Datos de la Junta Médica:      [fecha_junta, medico_solicitante, servicio, especialidades, diagnostico_establecido, relacion_junta, conclusiones, tac, contraste]
          Adicionar Médico Participante: [medico]            
