atencion_enfermeria_atencion_enfermeria:
  class: sfDoctrineRouteCollection
  options:
    model:                AtencionEnfermeria
    module:               atencion_enfermeria
    prefix_path:          /atencion_enfermeria
    column:               id
    with_wildcard_routes: true

solicitud_transfusion_sanguinea_solicitudes_transfusion_sanguinea:
  class: sfDoctrineRouteCollection
  options:
    model:                SolicitudTransfusionSanguinea
    module:               solicitudes_transfusion_sanguinea
    prefix_path:          /solicitudes_transfusion_sanguinea
    column:               id
    with_wildcard_routes: true

administracion_medicamento_administracion_medicamento:
  class: sfDoctrineRouteCollection
  options:
    model:                AdministracionMedicamento
    module:               administracion_medicamento
    prefix_path:          /administracion_medicamento
    column:               id
    with_wildcard_routes: true

solicitud_examen_laboratorio_solicitudes_examen_laboratorio:
  class: sfDoctrineRouteCollection
  options:
    model:                SolicitudExamenLaboratorio
    module:               solicitudes_examen_laboratorio
    prefix_path:          /solicitudes_examen_laboratorio
    column:               id
    with_wildcard_routes: true

autorizacion_autopsia_autorizaciones_autopsia:
  class: sfDoctrineRouteCollection
  options:
    model:                AutorizacionAutopsia
    module:               autorizaciones_autopsia
    prefix_path:          /autorizaciones_autopsia
    column:               id
    with_wildcard_routes: true

autorizacion_alta_solicitada_autorizaciones_alta_solicitada:
  class: sfDoctrineRouteCollection
  options:
    model:                AutorizacionAltaSolicitada
    module:               autorizaciones_alta_solicitada
    prefix_path:          /autorizaciones_alta_solicitada
    column:               id
    with_wildcard_routes: true

autorizacion_diagnostico_tratamiento_autorizaciones_diagnostico_tratamiento:
  class: sfDoctrineRouteCollection
  options:
    model:                AutorizacionDiagnosticoTratamiento
    module:               autorizaciones_diagnostico_tratamiento
    prefix_path:          /autorizaciones_diagnostico_tratamiento
    column:               id
    with_wildcard_routes: true

programacion_cirugia:
  class: sfDoctrineRouteCollection
  options:
    model:                ProgramacionCirugia
    module:               programacion_cirugia
    prefix_path:          /programacion_cirugia
    column:               id
    with_wildcard_routes: true  

detalle_orden_medica:
  class: sfDoctrineRouteCollection
  options:
    model:                DetalleOrdenMedica
    module:               detalle_ordenes
    prefix_path:          /detalle_ordenes
    column:               id
    with_wildcard_routes: true

internado:
  class: sfDoctrineRouteCollection
  options:
    model:                Internado
    module:               internados
    prefix_path:          /internados
    column:               id
    with_wildcard_routes: true

detalle_evolucion:
  class: sfDoctrineRouteCollection
  options:
    model:                DetalleEvolucion
    module:               detalles_evolucion
    prefix_path:          /detalles_evolucion
    column:               id
    with_wildcard_routes: true

detalle_enfermeria:
  class: sfDoctrineRouteCollection
  options:
    model:                DetalleEnfermeria
    module:               detalles_enfermeria
    prefix_path:          /detalles_enfermeria
    column:               id
    with_wildcard_routes: true

detalle_nursery:
  class: sfDoctrineRouteCollection
  options:
    model:                DetalleNursery
    module:               detalles_nursery
    prefix_path:          /detalles_nursery
    column:               id
    with_wildcard_routes: true

detalle_material:
  class: sfDoctrineRouteCollection
  options:
    model:                DetalleMaterial
    module:               detalles_material
    prefix_path:          /detalles_material
    column:               id
    with_wildcard_routes: true

atencion:
  class: sfDoctrineRouteCollection
  options:
    model:                Atencion
    module:               atenciones
    prefix_path:          /atenciones
    column:               id
    with_wildcard_routes: true

detalle_medicacion:
  class: sfDoctrineRouteCollection
  options:
    model:                DetalleMedicacion
    module:               detalles_medicacion
    prefix_path:          /detalles_medicacion
    column:               id
    with_wildcard_routes: true

apgar:
  class: sfDoctrineRouteCollection
  options:
    model:                Apgar
    module:               apgar
    prefix_path:          /apgar
    column:               id
    with_wildcard_routes: true

medico_particular:
  class: sfDoctrineRouteCollection
  options:
    model:                MedicoParticular
    module:               medicos_particulares
    prefix_path:          /medicos_particulares
    column:               id
    with_wildcard_routes: true

via_administracion:
  class: sfDoctrineRouteCollection
  options:
    model:                ViaAdministracion
    module:               vias_administracion
    prefix_path:          /vias_administracion
    column:               id
    with_wildcard_routes: true

notas_evolucion:
  class: sfDoctrineRouteCollection
  options:
    model:                NotasEvolucion
    module:               notas_evolucion
    prefix_path:          /notas_evolucion
    column:               id
    with_wildcard_routes: true

notas_enfermeria:
  class: sfDoctrineRouteCollection
  options:
    model:                NotasEnfermeria
    module:               notas_enfermeria
    prefix_path:          /notas_enfermeria
    column:               id
    with_wildcard_routes: true

signos_vitales_nursery:
  class: sfDoctrineRouteCollection
  options:
    model:                SignosVitalesNursery
    module:               nursery
    prefix_path:          /nursery
    column:               id
    with_wildcard_routes: true

solicitud_reposicion_material:
  class: sfDoctrineRouteCollection
  options:
    model:                SolicitudReposicionMaterial
    module:               reposicion_materiales
    prefix_path:          /reposicion_materiales
    column:               id
    with_wildcard_routes: true

solicitud_servicio:
  class: sfDoctrineRouteCollection
  options:
    model:                SolicitudServicio
    module:               solicitudes_servicios
    prefix_path:          /solicitudes_servicios
    column:               id
    with_wildcard_routes: true

solicitud_interconsulta:
  class: sfDoctrineRouteCollection
  options:
    model:                SolicitudInterconsulta
    module:               solicitudes_interconsultas
    prefix_path:          /solicitudes_interconsultas
    column:               id
    with_wildcard_routes: true

examen_fisico_recien_nacido:
  class: sfDoctrineRouteCollection
  options:
    model:                ExamenFisicoRecienNacido
    module:               recien_nacidos
    prefix_path:          /recien_nacidos
    column:               id
    with_wildcard_routes: true

junta_medica:
  class: sfDoctrineRouteCollection
  options:
    model:                JuntaMedica
    module:               juntas_medicas
    prefix_path:          /juntas_medicas
    column:               id
    with_wildcard_routes: true

servicio_mantenimiento:
  class: sfDoctrineRouteCollection
  options:
    model:                ServicioMantenimiento
    module:               servicios_mantenimiento
    prefix_path:          /servicios_mantenimiento
    column:               id
    with_wildcard_routes: true

orden_medica:
  class: sfDoctrineRouteCollection
  options:
    model:                OrdenMedica
    module:               ordenes_medicas
    prefix_path:          /ordenes_medicas
    column:               id
    with_wildcard_routes: true

# guiller 

informe_estadistico_adm_egreso_informeestadisticoadmegreso:
  class: sfDoctrineRouteCollection
  options:
    model:                InformeEstadisticoAdmEgreso
    module:               informeestadisticoadmegreso
    prefix_path:          /informeestadisticoadmegreso
    column:               id
    with_wildcard_routes: true

informe_estadistico_adm_egreso:
  class: sfDoctrineRouteCollection
  options:
    model:                InformeEstadisticoAdmEgreso
    module:               informeestadisticoAdmegreso
    prefix_path:          /informeestadisticoAdmegreso
    column:               id
    with_wildcard_routes: true

papeleta_pedido_material:
  class: sfDoctrineRouteCollection
  options:
    model:                PapeletaPedidoMaterial
    module:               papeletapedidomaterial
    prefix_path:          /papeletapedidomaterial
    column:               id
    with_wildcard_routes: true

solicitud_transfusion_sanguinea:
  class: sfDoctrineRouteCollection
  options:
    model:                SolicitudTransfusionSanguinea
    module:               solicitudtransfusionsanguinea
    prefix_path:          /solicitudtransfusionsanguinea
    column:               id
    with_wildcard_routes: true

lista_dieta:
  class: sfDoctrineRouteCollection
  options:
    model:                ListaDieta
    module:               listadieta
    prefix_path:          /listadieta
    column:               id
    with_wildcard_routes: true

atencion_enfermeria:
  class: sfDoctrineRouteCollection
  options:
    model:                AtencionEnfermeria
    module:               atencionenfermeria
    prefix_path:          /atencionenfermeria
    column:               id
    with_wildcard_routes: true

uso_hospitalario_uso_hospitalario:
  class: sfDoctrineRouteCollection
  options:
    model:                UsoHospitalario
    module:               uso_hospitalario
    prefix_path:          /uso_hospitalario
    column:               id
    with_wildcard_routes: true

resumen_alta:
  class: sfDoctrineRouteCollection
  options:
    model:                ResumenAlta
    module:               resumenalta
    prefix_path:          /resumenalta
    column:               id
    with_wildcard_routes: true

administracion_medicamento:
  class: sfDoctrineRouteCollection
  options:
    model:                AdministracionMedicamento
    module:               administracionmedicamento
    prefix_path:          /administracionmedicamento
    column:               id
    with_wildcard_routes: true

solicitud_examen_laboratorio:
  class: sfDoctrineRouteCollection
  options:
    model:                SolicitudExamenLaboratorio
    module:               solicitudexamenlaboratorio
    prefix_path:          /solicitudexamenlaboratorio
    column:               id
    with_wildcard_routes: true

programacion_cirugias:
  class: sfDoctrineRouteCollection
  options:
    model:                ProgramacionCirugias
    module:               programacioncirugias
    prefix_path:          /programacioncirugias
    column:               id
    with_wildcard_routes: true

autorizacion_autopsia:
  class: sfDoctrineRouteCollection
  options:
    model:                AutorizacionAutopsia
    module:               autorizacionesautopsia
    prefix_path:          /autorizacionesautopsia
    column:               id
    with_wildcard_routes: true

autorizacion_alta_solicitada:
  class: sfDoctrineRouteCollection
  options:
    model:                AutorizacionAltaSolicitada
    module:               autorizacionesaltasolicitada
    prefix_path:          /autorizacionesaltasolicitada
    column:               id
    with_wildcard_routes: true

autorizacion_diagnostico_tratamiento_autorizaciondiagnosticotratamientos:
  class: sfDoctrineRouteCollection
  options:
    model:                AutorizacionDiagnosticoTratamiento
    module:               autorizaciondiagnosticotratamientos
    prefix_path:          /autorizaciondiagnosticotratamientos
    column:               id
    with_wildcard_routes: true

autorizacion_diagnostico_tratamiento:
  class: sfDoctrineRouteCollection
  options:
    model:                AutorizacionDiagnosticoTratamiento
    module:               autorizaciondiagnosticoTratamientos
    prefix_path:          /autorizaciondiagnosticoTratamientos
    column:               id
    with_wildcard_routes: true

file_internacion_fileinternaciones:
  class: sfDoctrineRouteCollection
  options:
    model:                FileInternacion
    module:               fileinternaciones
    prefix_path:          /fileinternaciones
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: internados, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
