generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProgramacionCirugia
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          programacion_cirugia
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id
#    sfGuard_check_created_by: user_id

    config:      
      actions: ~
      fields:          
        operacion_fecha: { label: 'Fecha', date_format: dd/MM/yyyy }
        operacion_hora:  { label: 'Hora'}
        created_at:      { date_format: dd/MM/yyyy }
        updated_at:      { date_format: dd/MM/yyyy }
        creator:         { label: 'Responsable'}
        nombre_medico:   { label: 'Cirujano' }
        medico_id:       { label: 'Cirujano' }
      list:
        title: Listado Programacion Para Cirugias
        display: [ operacion_fecha, operacion_hora, nombre_medico, diagnostico_preoperatorio, creator]        
        object_actions:  
          _edit:        { credentials: [noAlta] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [Alta] }
          _delete:      { credentials: [noAlta] }
          imprimir:     { label: Imprimir, action: exportPdf, params: { onclick: "var w=window.open(this.href,'popupWindow','width=900,height=700,left=320,top=100,scrollbars=yes,menubar=no,resizable=no');w.focus();return false;"} }
        actions: {}
        batch_actions: {}
      filter:
        display: [ operacion_fecha, medico_id]
      form:   
        display: 
          Operacion:             [ operacion_fecha, operacion_hora, medico_id ]
          "&nbsp;":              [ diagnostico_preoperatorio, tratamiento_quirurgico, anestesia, otros ]
          "Examenes Auxiliares": [ examenes_auxiliares ]          
        actions:
          _delete: { credentials: [noAlta] }
          _list:   ~
          _save:   { credentials: [noAlta] }
      edit:            
        title: Edición Programación Para Cirugias
      new:        
        title: Nueva Programación Para Cirugias        
