generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProgramacionCirugia
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          programacion_cirugia
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:      
      actions: ~
      fields:          
        operacion_fecha: { date_format: dd/MM/yyyy }
        created_at: { date_format: dd/MM/yyyy }
        updated_at: { date_format: dd/MM/yyyy }
      list:
        title: Listado Programacion Para Cirugias
        display: [ operacion_fecha, operacion_hora,diagnostico_preoperatorio, tratamiento_quirurgico, anestesia, otros, descripcion_examenes_auxiliares, created_at, updated_at]        
        actions: {}
        batch_actions: {}
      filter:
        display: [ medico_id, operacion_fecha, diagnostico_preoperatorio, tratamiento_quirurgico, anestesia, otros, examenes_auxiliares ]
      form:   
        display: 
          Operacion:             [ internado_id, operacion_fecha, operacion_hora ]
          "&nbsp;":              [ diagnostico_preoperatorio, tratamiento_quirurgico, anestesia, otros ]
          "Examenes Auxiliares": [ examenes_auxiliares, created_at, updated_at ]          
      edit:            
        title: Edición Programación Para Cirugias
      new:        
        title: Nueva Programación Para Cirugias
        actions: {}