<?php

/**
 * ApgarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApgarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApgarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Apgar');
    }
    
    public static function getAllDetalles($examen_fisico_id)
    {
        $d = self::getInstance()->createQuery('ap')            
            ->where('ap.examen_fisico_recien_nacido_id = ?', $examen_fisico_id)
            ->orderBy('ap.id ASC')->execute();
        return $d;
    }   
    
}