<?php

/**
 * AtencionEnfermeriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AtencionEnfermeriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AtencionEnfermeriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AtencionEnfermeria');
    }
}