<?php

/**
 * AutorizacionAutopsiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AutorizacionAutopsiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AutorizacionAutopsiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AutorizacionAutopsia');
    }
}