<?php

/**
 * AutorizacionAltaSolicitadaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AutorizacionAltaSolicitadaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AutorizacionAltaSolicitadaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AutorizacionAltaSolicitada');
    }
}