<?php

/**
 * CamaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CamaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CamaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cama');
    }
}