<?php

/**
 * DetalleSolicitudExamenLaboratorioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleSolicitudExamenLaboratorioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleSolicitudExamenLaboratorioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleSolicitudExamenLaboratorio');
    }
}