<?php

/**
 * DetalleEvolucionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleEvolucionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleEvolucionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleEvolucion');
    }
}