<?php

/**
 * DetalleNurseryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleNurseryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleNurseryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleNursery');
    }
}