<?php

/**
 * DetalleMedicacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleMedicacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleMedicacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleMedicacion');
    }
    
    public static function getAllDetalles($sol_id)
    {
        $d = self::getInstance()->createQuery('det')            
            ->where('det.solicitud_interconsulta_id = ?', $sol_id)
            ->orderBy('det.id ASC')->execute();
        return $d;
    }
    
}