<?php

/**
 * DetalleMedicacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleMedicacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleMedicacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleMedicacion');
    }
}