<?php

/**
 * DetalleMaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleMaterialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleMaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleMaterial');
    }
}