<?php

/**
 * DetalleOrdenMedicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleOrdenMedicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleOrdenMedicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleOrdenMedica');
    }
}