<?php

/**
 * DetalleUsoHospitalarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleUsoHospitalarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleUsoHospitalarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleUsoHospitalario');
    }
       
    
    public static function getAllDetalles($uso_id)
    {
        $d = self::getInstance()->createQuery('det')            
            ->where('det.uso_hospitalario_id = ?', $uso_id)
            ->orderBy('det.id ASC')->execute();
        return $d;
    }
}