<?php

/**
 * DetalleSolicitudExamenLaboratorioClinicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleSolicitudExamenLaboratorioClinicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleSolicitudExamenLaboratorioClinicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleSolicitudExamenLaboratorioClinico');
    }
}