<?php

/**
 * DetalleUsoHospitalarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleUsoHospitalarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleUsoHospitalarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleUsoHospitalario');
    }
}