<?php

/**
 * DetalleAdminMedicamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleAdminMedicamentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleAdminMedicamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleAdminMedicamento');
    }
}