<?php

/**
 * DetallePapeletaPedidoMaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetallePapeletaPedidoMaterialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetallePapeletaPedidoMaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetallePapeletaPedidoMaterial');
    }
}