<?php

/**
 * EspecialidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EspecialidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EspecialidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Especialidad');
    }
}