<?php

/**
 * ExamenFisicoRecienNacidoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExamenFisicoRecienNacidoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExamenFisicoRecienNacidoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExamenFisicoRecienNacido');
    }
}