<?php

/**
 * FileInternacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FileInternacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FileInternacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FileInternacion');
    }
}