<?php

/**
 * FilialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FilialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FilialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Filial');
    }
}