<?php

/**
 * InformeEstadisticoAdmEgresoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InformeEstadisticoAdmEgresoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InformeEstadisticoAdmEgresoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InformeEstadisticoAdmEgreso');
    }
}