<?php

/**
 * Internado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Internado extends BaseInternado
{
    public $objetoDatosPersona = null;
    
    function getObjetoDatosPersona()
    {
        if ($this->objetoDatosPersona==null){
            $this->objetoDatosPersona = $this->getEsAfiliado() ? $this->getAfiliado() : $this->getPacienteOtroseguro();
        }        
        return $this->objetoDatosPersona;
    }
    
    
    function getNombreCompleto()
    {        
        if ($this->objetoDatosPersona==null){
            $this->objetoDatosPersona = $this->getEsAfiliado() ? $this->getAfiliado() : $this->getPacienteOtroseguro();
        }        
        return $this->objetoDatosPersona->getNombre() . ' ' . $this->objetoDatosPersona->getPaterno() . ' ' . $this->objetoDatosPersona->getMaterno();
    }
    

    function getDescripcionEsAfiliado()
    {
        return $this->getEsAfiliado() ? 'Si' : 'No'; 
    }
    
    function getDescripcionFechaHora($formatF='d/m/Y', $formatH='H:i')
    {
        return $this->getDateTimeObject('fecha')->format($formatF) . ' ' . substr($this->getHora(), 0, 5); 
    }
    
    function getDescripcionAltaFechaHora($formatF='d/m/Y',$formatH='H:i')
    {   
        return $this->getDateTimeObject('altaFecha')->format($formatF) . ' ' . substr($this->getHora(), 0, 5);

    }
        
    public function getEmpresa()
    {
        if($this->Afiliado->getEmpresa()==null)
            return "Otro seguro";
        else
            return $this->Afiliado->getEmpresa();
    }

    public function getMatricula()
    {
        return $this->Afiliado->getMatricula();
    }
    
    public function getUbicacion()
    {
        return 'Planta: '.$this->Cama->Pieza->Planta->getNombre().' Pieza: '.$this->Cama->Pieza->getNombre().' Cama: '.$this->Cama->getCodigo();

    }
    
}
