<?php

/**
 * Internado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Internado extends BaseInternado
{
    public $objetoDatosPersona = null;
    
    function getObjetoDatosPersona()
    {
        if ($this->objetoDatosPersona==null){
            $this->objetoDatosPersona = $this->getEsAfiliado() ? $this->getAfiliado() : $this->getPacienteOtroseguro();
        }        
        return $this->objetoDatosPersona;
    }
    
    
    function getNombreCompleto()
    {        
        if ($this->objetoDatosPersona==null){
            $this->objetoDatosPersona = $this->getEsAfiliado() ? $this->getAfiliado() : $this->getPacienteOtroseguro();
        }        
        return $this->objetoDatosPersona->getNombre() . ' ' . $this->objetoDatosPersona->getPaterno() . ' ' . $this->objetoDatosPersona->getMaterno();
    }
}
