<?php

/**
 * JuntaMedicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JuntaMedicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JuntaMedicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JuntaMedica');
    }
}