<?php

/**
 * MedicoParticularTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedicoParticularTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedicoParticularTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedicoParticular');
    }
    
    public static function selectMedicos($junta_id)
    {
        
        $q = Doctrine_Query::create()
                    ->from('MedicoParticular mp')
                    ->leftJoin('mp.JuntaMedica jm')
                    ->where('mp.junta_medica_id = ?', $junta_id)
                    ->orderBy('mp.id ASC');
        return $q;
    }
}
