<?php

/**
 * MedicoParticularTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedicoParticularTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedicoParticularTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedicoParticular');
    }
}