<?php

/**
 * NotasEnfermeriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotasEnfermeriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotasEnfermeriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotasEnfermeria');
    }
}