<?php

/**
 * NotaEvolucionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaEvolucionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaEvolucionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaEvolucion');
    }
}