<?php

/**
 * NotaEnfermeriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaEnfermeriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaEnfermeriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaEnfermeria');
    }
}