<?php

/**
 * OrdenMedicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdenMedicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdenMedicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdenMedica');
    }
}