<?php

/**
 * PacienteOtroseguroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PacienteOtroseguroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PacienteOtroseguroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PacienteOtroseguro');
    }
}