<?php

/**
 * PapeletaPedidoMaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PapeletaPedidoMaterialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PapeletaPedidoMaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PapeletaPedidoMaterial');
    }
}