<?php

/**
 * ProgramacionCirugia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProgramacionCirugia extends BaseProgramacionCirugia
{

    public function getDescripcionExamenesAuxiliares($sepatator=", ") 
    {
        $res =array();
        foreach ($this->getExamenesAuxiliares() as $ex){
            $res[] = ProgramacionCirugiaTable::getDescripcion_examen_auxiliar($ex);
        }
        return implode($sepatator, $res);
    }    
    
    
    function getNombreMedico()
    {          
        return $this->Medico->getNombrec();
    }
}