<?php

/**
 * ResumenAltaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResumenAltaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResumenAltaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResumenAlta');
    }
}