<?php

/**
 * SolicitudInterconsultaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SolicitudInterconsultaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SolicitudInterconsultaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SolicitudInterconsulta');
    }
}