<?php

/**
 * SolicitudReposicionMaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SolicitudReposicionMaterialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SolicitudReposicionMaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SolicitudReposicionMaterial');
    }
}