<?php

/**
 * SolicitudTransfusionSanguinea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SolicitudTransfusionSanguinea extends BaseSolicitudTransfusionSanguinea
{
    
    public function getDescripcionRequiereTransfusionDe() 
    {
        return SolicitudTransfusionSanguineaTable::getDescripcion_requiere_transfusion_de($this->getRequiereTransfusionDe());
    }
    
    
    public function getDescripcionCumplirseEnforma()
    {
        return SolicitudTransfusionSanguineaTable::getDescripcion_cumplirse_enforma($this->getCumplirseEnforma());
    }
    
}
