<?php

/**
 * SolicitudExamenLaboratorioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SolicitudExamenLaboratorioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SolicitudExamenLaboratorioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SolicitudExamenLaboratorio');
    }
}