<?php

/**
 * SolicitudExamenLaboratorioClinicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SolicitudExamenLaboratorioClinicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SolicitudExamenLaboratorioClinicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SolicitudExamenLaboratorioClinico');
    }
}