<?php

/**
 * SolicitudServicioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SolicitudServicioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SolicitudServicioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SolicitudServicio');
    }
}