<?php

/**
 * TipoExamenLaboratorioClinicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoExamenLaboratorioClinicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoExamenLaboratorioClinicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoExamenLaboratorioClinico');
    }
}