<?php

/**
 * UsoHospitalarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsoHospitalarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsoHospitalarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsoHospitalario');
    }
}