<?php

/**
 * ViaAdministracionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ViaAdministracionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ViaAdministracionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ViaAdministracion');
    }
}