<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
    
    public function getDescripcionTipo()
    {
        return sfGuardUserTable::getDescripcione_tipo($this->getTipo());
    }
    
    public function getCustomTipoEmpleadoId()
    {
        return $this->getTipo() . $this->getEmpleadoId();
    }
    
    public function setCustomTipoEmpleadoId($val)
    {
       $this->setTipo(substr($val, 0,1));
       $this->setEmpleadoId(intval(substr($val, 1)));
    }
}
