<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{  
    
    /*
     * tipo describe con que tabla se vincula el usuario
     * (actualmente 2 tablas medico y empleado)
     */
    const HCPS_USER_TIPO_MEDICO = 'm';
    const HCPS_USER_TIPO_EMPLEADO = 'e';    
    
    static $descripciones_tipo = array('m'=>'Medico', 'e'=>'Empleado');
    
    static public function getDescripcione_tipo($tipo,$default=null)
    {
        if (array_key_exists($tipo, self::$descripciones_tipo)){
            return self::$descripciones_tipo[$tipo];
        }
        return $default;
    }    
}