<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hcps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
    private $hcps_user = false;
    
    public function getDescripcionTipo()
    {
        return sfGuardUserTable::getDescripcione_tipo($this->getTipo());
    }
    
    public function getCustomTipoEmpleadoId()
    {
        return $this->getTipo() . $this->getEmpleadoId();
    }
    
    public function setCustomTipoEmpleadoId($val)
    {
       $this->setTipo(substr($val, 0,1));
       $this->setEmpleadoId(intval(substr($val, 1)));
    }
    
    
    /**
    * Returns the string representation of the object: "Full Name (username)"
    *
    * @return string
    */
    public function __toString()
    {
        return (string) $this->getNombreCompleto().' ('.$this->getUsername().')';
    }
    
    
    
        /**
    * Returns the first and last name of the user concatenated together
    *
    * @return string $name
    */
    public function getNombreCompleto()
    {   
        $u = $this->getHcpsUser();        
        if (is_object($u)){            
            return trim($u->getNombreCompleto());
        }
        return '';
    }
    
    
    public function getHcpsUser()            
    {
        if ($this->hcps_user===false){
            if ($this->getTipo()==sfGuardUserTable::HCPS_USER_TIPO_MEDICO ){                
                $this->hcps_user = MedicoTable::getInstance()->find($this->getEmpleadoId());
            }
            elseif($this->getTipo()==sfGuardUserTable::HCPS_USER_TIPO_EMPLEADO){                
                $this->hcps_user = EmpleadoTable::getInstance()->find($this->getEmpleadoId());
            }
        }
        
        return $this->hcps_user;
    }
            
    
    
}
