generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ResumenAlta
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          resumen_alta
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id
    BorradoConTipoMotivoFields:  {motivo: MotivoBorrado ,tipo: TipoBorrado}

    config:
      actions: ~
      fields: 
        diagnostico_provisional:      { label: "Diag. Provisional" }
        diagnostico_definitivo:       { label: "Diag. Definitivo"  }
        operaciones:                  { label: "Operaciones"  }
        anamesis_examenfisico:        { label: "Anamesis y Examen Físico"  } 
        hallazgos_labo_interconsultas:     { label: "Lab. Rayos X e Interconsultas"  } 
        evolucion_complicacion:            { label: "Evolución en el Hospital"  } 
        condicion_tratamiento_pronostico:  { label: "Referencia final"  }
        created_at:           { date_format: dd/MM/yyyy }
        updated_at:           { date_format: dd/MM/yyyy }
        creator:              { label: Responsable }
      list:  
        title: Listado Resumen Alta
        display:    [diagnostico_provisional, diagnostico_definitivo, operaciones, hallazgos_labo_interconsultas, evolucion_complicacion, condicion_tratamiento_pronostico]
        object_actions:  
          ver_detalle:  {label: Ver Detalle, action: edit, credentials: [[medico, ver_todo_datos]] }
          _suspender:   {label: Suspender, credentials: [noAlta, crear, medico], onClickJsFunction: "dijit.byId('panel_suspender').iniciar"}
          _anular:      {label: Anular, credentials: [noAlta, crear, medico], onClickJsFunction: "dijit.byId('panel_anular').iniciar" }
        actions: {}
        batch_actions: {}
      filter: 
        display: [diagnostico_provisional, diagnostico_definitivo]
      form: 
        display: [diagnostico_provisional, diagnostico_definitivo, operaciones, anamesis_examenfisico, hallazgos_labo_interconsultas, evolucion_complicacion, condicion_tratamiento_pronostico]
        actions:
#          _delete: { credentials: [noAlta] }
          _list:   ~
#          _save:   { credentials: [noAlta] }
      edit:    
        title: Edición Resumen Alta
      new:        
        title: Nueva Resumen Alta
        actions:
          _list:   ~
          _save:   ~