generator:
  class: sfDoctrineGenerator
  param:
    model_class:           AutorizacionAutopsia
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          autorizacion_autopsia_autorizaciones_autopsia
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id
    sfGuard_check_created_by: user_id
    AnulableField:         MotivoAnulacion

    config:
      actions: ~
      fields:        
        fecha_hora:       { date_format: 'dd/MM/yyyy hh:mm' } 
        created_at:       { date_format: dd/MM/yyyy }
        updated_at:       { date_format: dd/MM/yyyy }
        creator:          { label: 'Responsable' }
        nombre_familiar1: {label: Nombre del Familiar}
        tipo_parentesco1: {label: Parentezco}
        ci_familiar1:     {label: C.I.}
        nombre_familiar2: {label: Nombre del Familiar}
        tipo_parentesco2: {label: Parentezco}
        ci_familiar2:     {label: C.I.}
        nombre_familiar3: {label: Nombre del Familiar}
        tipo_parentesco3: {label: Parentezco}
        ci_familiar3:     {label: C.I.}
      list:   
        title: Listado Autorizacion Autopsia
        display: [ fecha_hora, nombre_familiar1, tipo_parentesco1, ci_familiar1, creator]        
        object_actions:  
#          _edit:        { credentials: [noAlta, crear, enfermera] }
          ver_detalle:  {label: Ver Detalle, action: edit, credentials: [[enfermera, ver_todo_datos]] }
          _delete:      {label: Anular, credentials: [noAlta, crear, enfermera], onClickJsFunction: "dijit.byId('panel_anular').iniciar", AnulableField: 'MotivoAnulacion' }
          imprimir:     {label: Imprimir, action: exportPdf, params: { onclick: "var w=window.open(this.href,'popupWindow','width=900,height=700,left=320,top=100,scrollbars=yes,menubar=no,resizable=no');w.focus();return false;"} }
        actions: {}
        batch_actions: {}
      filter:  
        display: [ fecha_hora, nombre_familiar1, ci_familiar1 ]
      form:    
        display: 
          'Familiar 1': [ internado_id, nombre_familiar1, tipo_parentesco1, ci_familiar1 ]
          'Familiar 2': [ nombre_familiar2, tipo_parentesco2, ci_familiar2 ]
          'Familiar 3': [ nombre_familiar3, tipo_parentesco3, ci_familiar3 ]
          '&nbsp;' :   [ fecha_hora ]
        fields:
          nombre_familiar1: { label: Nombre }
          nombre_familiar2: { label: Nombre }
          nombre_familiar3: { label: Nombre }
          tipo_parentesco1: { label: Tipo Parentezco }
          tipo_parentesco2: { label: Tipo Parentezco }
          tipo_parentesco3: { label: Tipo Parentezco }
          ci_familiar1 :    { label: CI }
          ci_familiar2 :    { label: CI }
          ci_familiar3 :    { label: CI }
        actions:
#          _delete: { credentials: [noAlta, crear, enfermera] }
          _list:   ~
#          _save:   { credentials: [noAlta, crear, enfermera] }
      edit:            
        title: Edición Autorizacion Autopsia
      new:        
        title: Nueva Autorizacion Autopsia     
        actions:
          _list:   ~
          _save:   ~