generator:
  class: sfDoctrineGenerator
  param:
    model_class:           UsoHospitalario
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          uso_hospitalario_uso_hospitalario
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    
        display:
          Datos Uso Hospitalario: [ lugar, fecha, medico_id, codigo, especialidad ]
          Detalle:   [ DetallesUsoHospitalario ]
      edit:    ~
      new:     ~
