generator:
  class: sfDoctrineGenerator
  param:
    model_class:           UsoHospitalario
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          uso_hospitalario
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id
    
    config:
      actions: ~
      fields: 
        fecha:      { date_format: 'dd/MM/yyyy' }
        created_at: { date_format: dd/MM/yyyy }
        updated_at: { date_format: dd/MM/yyyy }
      list: 
        title: Listado Recetas Uso Hospitalario
        display: [ lugar, fecha, codigo, especialidad]
        object_actions:  
          _edit:        { credentials: [noHistory] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [siHistory] }
          _delete:      { credentials: [noHistory] }
        actions: {}
        batch_actions: {}
      filter: 
        display: [ lugar, fecha, codigo, especialidad, created_at, updated_at ]
      form:
        actions:
          _delete: ~
          _list:   ~
          _save:   { credentials: [noHistory] }
      edit:    
        title: Edición Recetas Uso Hospitalario
        display:
          Datos Uso Hospitalario: [ internado_id, lugar, fecha, codigo, especialidad ]
          Items Adicionados:      [ _listado_items ]
      new:        
        title: Nueva Recetas Uso Hospitalario
        display:
          Datos Uso Hospitalario: [ internado_id, lugar, fecha, codigo, especialidad ]
          Adicionar Items:        [ _listado_items ]        
          
