generator:
  class: sfDoctrineGenerator
  param:
    model_class:           UsoHospitalario
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          uso_hospitalario
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id
    sfGuard_check_created_by: user_id
    
    config:
      actions: ~
      fields: 
        fecha:         { date_format: 'dd/MM/yyyy' }
        created_at:    { date_format: dd/MM/yyyy }
        updated_at:    { date_format: dd/MM/yyyy }
        creator:       { lable: Responsable }
        nombre_medico: {label: Medico}
        medico_id:     {label: Medico}
      list: 
        title: Listado Recetas Uso Hospitalario
        display: [ fecha, codigo, nombre_medico, especialidad, creator]
        object_actions:  
          _edit:        { credentials: [noAlta, crear, enfermera] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [[enfermera, ver_todo_datos], alta] }
          _delete:      { credentials: [noAlta, crear, enfermera] }
        actions: {}
        batch_actions: {}
      filter: 
        display: [ fecha, codigo ]
      form:
        actions:
          _delete: { credentials: [noAlta, crear, enfermera] }
          _list:   ~
          _save:   { credentials: [noAlta, crear, enfermera] }
      edit:    
        title: Edición Recetas Uso Hospitalario
        display:
          Datos Uso Hospitalario: [ internado_id, lugar, fecha, codigo, medico_id, especialidad ]
          Items Adicionados:      [ _listado_items ]
      new:        
        title: Nueva Recetas Uso Hospitalario
        display:
          Datos Uso Hospitalario: [ internado_id, lugar, fecha, codigo, medico_id, especialidad ]
          Adicionar Items:        [ _listado_items ]        
          
