generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DetallePapeletaPedidoMaterial
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          detalle_papeleta_pedido_material
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    
        actions:          
          _save: { credentials: [noHistory] }
      edit:    ~
      new:     ~
