generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolicitudServicio
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solicitud_servicio
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  
        creator:    {label: 'Reponsable'}
        created_at: {label: 'Fecha', date_format: 'dd/MM/yyyy'}
      list:    
        title: Solicitudes de Servicios
        display: [created_at, atencion, para, diagnostico_presuncion, creator]
        object_actions:  
          _edit:        { credentials: [noHistory] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [siHistory] }
          _delete:      { credentials: [noHistory] }
        actions: {}
        batch_actions: {}
      filter:  
        display: [atencion_id]
      form:   
        actions:
          _list: ~
          _save: { credentials: [noHistory] }
      edit:    
        title: Editar Solicitud de Servicio        
      new:     
        title: Nueva Solicitud de Servicios        