generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolicitudServicio
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solicitud_servicio
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id
#    sfGuard_check_created_by: user_id

    config:
      actions: ~
      fields:  
        creator:  {label: 'Reponsable'}
        fecha:    {label: 'Fecha', date_format: 'dd/MM/yyyy'}
      list:    
        title: Solicitudes de Servicios
        display: [fecha, atencion, para, diagnostico_presuncion, creator]
        object_actions:  
          _edit:        { credentials: [noAlta] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [Alta] }
          _delete:      { credentials: [noAlta] }
        actions: {}
        batch_actions: {}
      filter:  
        display: [fecha, atencion_id]
      form:   
        actions:
          _delete: { credentials: [noAlta] }
          _list:   ~
          _save:   { credentials: [noAlta] }
      edit:    
        title: Editar Solicitud de Servicio        
      new:     
        title: Nueva Solicitud de Servicios        