generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PapeletaPedidoMaterial
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          papeleta_pedido_material
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  
        fecha_solicitud: { date_format: 'dd/MM/yyyy' }
        created_at:      { date_format: dd/MM/yyyy }
        updated_at:      { date_format: dd/MM/yyyy }
      list:    
        title: Listado Pepeleta Pedido material
        display: [ fecha_solicitud, created_at, updated_at ]
        object_actions:  
          _edit:        { credentials: [noHistory] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [siHistory] }
          _delete:      { credentials: [noHistory] }
        actions: {}
        batch_actions: {}
      filter:  
        display: [ fecha_solicitud ]
      form:    
        display:           
          Datos Papeleta Pedido Material: [ internado_id, fecha_solicitud ]
          Items Adicionados:              [ _listado_items ]
        actions:
          _list: ~
          _save: { credentials: [noHistory] }
      edit:    
        title: Edición Pepeleta Pedido material
      new:        
        title: Nueva Pepeleta Pedido material
