generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PapeletaPedidoMaterial
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          papeleta_pedido_material
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id
    sfGuard_check_created_by: user_id
    BorradoConTipoMotivoFields:  {motivo: MotivoBorrado ,tipo: TipoBorrado}

    config:
      actions: ~
      fields:  
        fecha_solicitud: { date_format: 'dd/MM/yyyy' }
        created_at:      { date_format: dd/MM/yyyy }
        updated_at:      { date_format: dd/MM/yyyy }
        creator:         { label: Responsable }
      list:    
        title:          Listado Pepeleta Pedido material
        display:        [ fecha_solicitud, creator ]
        object_actions:  
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [[enfermera, ver_todo_datos]] }
          _suspender:   {label: Suspender, credentials: [noAlta, crear, enfermera], onClickJsFunction: "dijit.byId('panel_suspender').iniciar"}
          _anular:      {label: Anular, credentials: [noAlta, crear, enfermera], onClickJsFunction: "dijit.byId('panel_anular').iniciar" }
        actions: {}
        batch_actions: {}
      filter:  
        display: [ fecha_solicitud ]
      form:            
        actions:          

          _list:   ~
          _save:   { credentials: [noAlta, crear, enfermera] }
      edit:    
        title: Edición Pepeleta Pedido material
        display:
          Datos Papeleta Pedido Material: [ internado_id, fecha_solicitud ]
          Materiales Adicionados:         [ _listado_items ]
      new:        
        title: Nueva Pepeleta Pedido material
        display:
          Datos Papeleta Pedido Material: [ internado_id, fecha_solicitud ]
          Adicionar Material:             [ _listado_items ]