<?php

/**
 * PluginsfGuardUserGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardUserGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardUserGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardUserGroup');
    }
}