<?php

/**
 * PluginsfGuardGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardGroup');
    }
}