<?php

/**
 * PluginsfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardUser');
    }
}