generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolicitudExamenLaboratorioClinico
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solicitud_examen_laboratorio_clinico
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:          
        fecha: { date_format: 'dd/MM/yyyy hh:mm' }
        created_at: { date_format: dd/MM/yyyy }
        updated_at: { date_format: dd/MM/yyyy }
      list:  
        title: Listado Solicitudes Examen Laboratorio
        display: [ material_enviado, otros_examenes, diagnostico_presuntivo, lugar, fecha, created_at, updated_at ]
        actions: {}
        batch_actions: {}
      filter:
        display: [ material_enviado, otros_examenes, diagnostico_presuntivo, lugar, fecha ]
      form:    
        display:
          "Examenes: ": [ internado_id, _lista_tipos_examenes ]
          "&nbsp; ":   [ material_enviado, otros_examenes, diagnostico_presuntivo, lugar, fecha ]
      edit:    
        title: Edición Listado Solicitudes Examen Laboratorio
      new:        
        title: Nueva Listado Solicitudes Examen Laboratorio

