generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolicitudExamenLaboratorioClinico
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solicitud_examen_laboratorio_clinico
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id
    sfGuard_check_created_by: user_id

    config:
      actions: ~
      fields:          
        fecha:      { date_format: 'dd/MM/yyyy' }
        created_at: { date_format: dd/MM/yyyy }
        updated_at: { date_format: dd/MM/yyyy }
        creator:    { label: Responsable }
      list:  
        title: Listado Solicitudes Examen Laboratorio
        display: [ fecha, material_enviado, otros_examenes, diagnostico_presuntivo, creator]
        object_actions:  
          _edit:        { credentials: [noAlta, crear, medico] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [[medico, ver_todo_datos], alta] }
          _delete:      { credentials: [noAlta, crear, medico] }
        actions: {}
        batch_actions: {}
      filter:
        display: [ fecha, diagnostico_presuntivo ]
      form:    
        display:
          "Examenes: ": [ internado_id, _lista_tipos_examenes ]
          "&nbsp; ":   [ material_enviado, otros_examenes, diagnostico_presuntivo, lugar, fecha ]
        actions:
#          _delete: { credentials: [noAlta, crear, medico] }
          _list:   ~
          _save:   { credentials: [noAlta, crear, medico] }
      edit:    
        title: Edición Listado Solicitudes Examen Laboratorio
      new:        
        title: Nueva Listado Solicitudes Examen Laboratorio