generator:
  class: sfDoctrineGenerator
  param:
    model_class:           NotasEnfermeria
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          notas_enfermeria
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id
    sfGuard_check_created_by: user_id
    AnulableField:         MotivoAnulacion

    config:
      actions: ~
      fields:  
        fecha:      { date_format: 'dd/MM/yyyy' }
        creator:    {label: 'Responsable'}
      list:    
        title: Notas de Enfermeria
        display: [fecha, hora, procedimientos, observaciones, creator]
        object_actions:  
#          _edit:        { credentials: [noHistory] }
          ver_detalle:  {label: Ver Detalle, action: edit, credentials: [[enfermera, ver_todo_datos]] }
          _delete:      {label: Anular, credentials: [noAlta, crear, enfermera], onClickJsFunction: "dijit.byId('panel_anular').iniciar", AnulableField: 'MotivoAnulacion'}
        actions: {}
        batch_actions: {}
      filter:  
        display: [fecha]
      form:    
        display:
          S.O.P.E. Sujeto - Objetivo - Plan - Evaluación: [fecha, hora, procedimientos, observaciones]
        actions:
#          _delete: { credentials: [noAlta, crear, enfermera] }
          _list:   ~
#          _save:   { credentials: [noAlta, crear, enfermera] }        
      edit:
        title: Editar Nota de Enfermeria        
      new:     
        title: Nueva Nota de Enfermería
        actions:
          _list:   ~
          _save:   ~