generator:
  class: sfDoctrineGenerator
  param:
    model_class:           NotasEnfermeria
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          notas_enfermeria
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  ~
      list:    
        title: Notas de Enfermeria
        display: [fecha, hora, procedimientos]
        object_actions:  
          _edit:        { credentials: [noHistory] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [siHistory] }
          _delete:      { credentials: [noHistory] }
        actions: {}
        batch_actions: {}
      filter:  
        display: [fecha]
      form:    ~
      edit:    
        title: Editar Nota de Enfermeria
        actions:
          _save: ~
      new:     
        title: Nueva Nota de Enfermeria
        actions:
          _save: ~
          _save_and_add: ~