generator:
  class: sfDoctrineGenerator
  param:
    model_class:           NotasEnfermeria
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          notas_enfermeria
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  
        fecha: { date_format: 'dd/MM/yyyy' }
      list:    
        title: Notas de Enfermeria
        display: [fecha, hora, procedimientos, observaciones]
        object_actions:  
          _edit:        { credentials: [noHistory] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [siHistory] }
          _delete:      { credentials: [noHistory] }
        actions: {}
        batch_actions: {}
      filter:  
        display: [fecha]
      form:    
        display:
          S.O.P.E. Sujeto - Objetivo - Plan - Evaluación: [fecha, hora, procedimientos, observaciones]
      edit:    
        title: Editar Nota de Enfermería
        actions:
          _list: ~
          _save: { credentials: [noHistory] }
      edit:    
        title: Editar Nota de Enfermeria        
      new:     
        title: Nueva Nota de Enfermería
        actions:
          _list: ~
          _save: ~
