generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DetalleMaterial
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          detalle_material
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  ~
      list:    
        actions: {}
        batch_actions: {}
      filter:  ~
      form:    ~
      edit:    
        actions:
          _delete:    ~
          _save:      ~
          _addcomment:  ~
      new:     
        actions:
          _save: ~
          _save_and_add: ~