generator:
  class: sfDoctrineGenerator
  param:
    model_class:           AutorizacionAltaSolicitada
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          autorizacion_alta_solicitada_autorizaciones_alta_solicitada
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:       internado_id
    sfGuard_check_created_by: user_id
    BorradoConTipoMotivoFields:  {motivo: MotivoBorrado ,tipo: TipoBorrado}
    
    config:
      actions: ~
      fields:          
        fecha_hora:      { date_format: 'dd/MM/yyyy hh:mm' }
        created_at:      { date_format: dd/MM/yyyy }
        updated_at:      { date_format: dd/MM/yyyy }
        creator:         { label: 'Responsable' }
        nombre_familiar: {label: Nombre del Familiar}
        tipo_parentesco: {label: Parentezco}
        ci_familiar:     {label: C.I.}
        
      list:    
        title: Listado Autorizacion Alta Solicitada
        display: [ fecha_hora, nombre_familiar, ci_familiar, creator]        
        object_actions:  
#          _edit:        { credentials: [noAlta, crear, enfermera] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [[enfermera, ver_todo_datos]] }
          _suspender:   {label: Suspender, credentials: [noAlta, crear, enfermera], onClickJsFunction: "dijit.byId('panel_suspender').iniciar"}
          _anular:      {label: Anular, credentials: [noAlta, crear, enfermera], onClickJsFunction: "dijit.byId('panel_anular').iniciar" }
          imprimir:     { credentials: [noAlta, crear, enfermera] }
        actions: {}
        batch_actions: {}
      filter:  
        display: [ fecha_hora, nombre_familiar,ci_familiar ]
      form:    
        display: [ internado_id,nombre_familiar,ci_familiar,fecha_hora ]
        actions:
#          _delete: { credentials: [noAlta, crear, enfermera] }
          _list:   ~
#          _save:   { credentials: [noAlta, crear, enfermera] }
      edit:    
        title: Edición Autorizacion Alta Solicitada
      new:        
        title: Nueva Autorizacion Alta Solicitada
        actions:
          _list:   ~
          _save:   ~