generator:
  class: sfDoctrineGenerator
  param:
    model_class:           AutorizacionAltaSolicitada
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          autorizacion_alta_solicitada_autorizaciones_alta_solicitada
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:       internado_id
    
    config:
      actions: ~
      fields:          
        fecha_hora: { date_format: 'dd/MM/yyyy hh:mm' }
        created_at: { date_format: dd/MM/yyyy }
        updated_at: { date_format: dd/MM/yyyy }
      list:    
        title: Listado Autorizacion Alta Solicitada
        display: [ internado_id,nombre_familiar,ci_familiar,fecha_hora, created_at, updated_at]        
        object_actions:  
          _edit:        { credentials: [noHistory] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [siHistory] }
          _delete:      { credentials: [noHistory] }
        actions: {}
        batch_actions: {}
        object_actions:
          _edit: ~
          _delete: ~
          imprimir: {label: Imprimir, action: exportPdf}
      filter:  
        display: [ nombre_familiar,ci_familiar,fecha_hora ]
      form:    
        display: [ internado_id,nombre_familiar,ci_familiar,fecha_hora ]
        actions:
          _delete: ~
          _list: ~
          _save: { credentials: [noHistory] }
      edit:    
        title: Edición Autorizacion Alta Solicitada
      new:        
        title: Nueva Autorizacion Alta Solicitada
        actions: {}
