## YAML Template.
---
index:
  credentials: [[enfermera, ver_todo_datos]]
new:
  credentials: [[crear, enfermera],[crear, medico]]
edit:
  credentials: [[enfermera, ver_todo_datos]]
delete: 
  credentials: [[crear, enfermera],[crear, medico]]