generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ServicioMantenimiento
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          servicio_mantenimiento
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  ~
      list:    
        title: Solicitudes de Mantenimiento
        display: [fecha_solicitante, solicitante, sector, trabajo_solicitado]
        object_actions:  
          _edit:        { credentials: [noAlta] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [Alta] }
          _delete:      { credentials: [noAlta] }
        actions: {}
        batch_actions: {}
      filter:  
        display: [fecha_solicitante, sector]
      form:    ~
      edit:    
        title: Editar Solicitud de Servicio de Mantenimiento
        actions:
          _save: ~
      new:     
        title: Nueva Solicitud de Servicio de Mantenimiento
        actions:
          _save: ~
          _save_and_add: ~