generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Atencion
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          atencion
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  ~
      list:    
        title: Lista de Atenciones
        object_actions:  
          _edit:        { credentials: [noHistory] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [siHistory] }
          _delete:      { credentials: [noHistory] }
        actions: {}
        batch_actions: {}
      filter:  
        display: [nombre]
      form:    
        actions:
          _list: ~
          _save: { credentials: [noAlta] }
      edit:    
        title: Editar Atencion %%nombre%%
      new:    
        title: Nueva Atencion
