generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ExamenFisicoRecienNacido
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          examen_fisico_recien_nacido
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  ~
      list:    
        title: Examen Físico del Recien Nacido
        display: [ap_paterno, ap_materno, sexo, peso_nacimiento]
        object_actions:  
          _edit:        { credentials: [noHistory] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [siHistory] }
          _delete:      { credentials: [noHistory] }
        actions: {}
        batch_actions: {}
      filter:  
        display: [ap_paterno, ap_materno, sexo]
      form:    
        actions:
          _list: ~
          _save: { credentials: [noHistory] }        
      edit:    
        title: Editar Recien Nacido %%ap_paterno%% %%ap_materno%%
        display:
          Examen Físico del Recien Nacido: [ap_paterno, ap_materno, fecha_nacimiento, sexo, peso_nacimiento, talla, circunferencia_torax, numero_cuna, fecha_adminision, fecha_egreso]
          Apgar: [apgar]
      new:     
        title: Nuevo Recien Nacido
        display:
          Examen Físico del Recien Nacido: [ap_paterno, ap_materno, fecha_nacimiento, sexo, peso_nacimiento, talla, circunferencia_torax, numero_cuna, fecha_adminision, fecha_egreso]
          Adicionar Apgar: [apgar]