generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ExamenFisicoRecienNacido
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          examen_fisico_recien_nacido
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id
    sfGuard_check_created_by: user_id
    BorradoConTipoMotivoFields:  {motivo: MotivoBorrado ,tipo: TipoBorrado}

    config:
      actions: ~
      fields:  
        fecha_nacimiento: {label: 'Nacimiento', date_format: 'dd/MM/yyyy'}
        ap_paterno:       {label: 'Apellido Paterno'}
        ap_materno:       {label: 'Apellido Materno'}
        peso_nacimiento:  {label: 'Peso'}
        numero_cuna:      {label: 'Cuna'}
        creator:          {label: 'Responsable'}
      list:    
        title: Examen Físico del Recien Nacido
        display: [fecha_nacimiento, ap_paterno, ap_materno, numero_cuna, sexo, creator]
        object_actions:  
          imprimir:        { label: Imprimir, action: exportPdf, params: { onclick: "var w=window.open(this.href,'popupWindow','width=900,height=700,left=320,top=100,scrollbars=yes,menubar=no,resizable=no');w.focus();return false;" } } 
          ver_detalle:     { label: Ver Detalle, action: edit, credentials: [[enfermera, ver_todo_datos]] }
          ver_apgar_ form: { label: Ver Apgar, action: verApgarForm }
          _suspender:      { label: Suspender, credentials: [noAlta, crear, enfermera], onClickJsFunction: "dijit.byId('panel_suspender').iniciar"}
          _anular:         { label: Anular, credentials: [noAlta, crear, enfermera], onClickJsFunction: "dijit.byId('panel_anular').iniciar" }
        actions: {}
        batch_actions: {}
      filter:  
        display: [fecha_nacimiento, ap_paterno, ap_materno]
      form:    
        actions:
#          _delete: { credentials: [noAlta, crear, enfermera] }
          _list:   ~
          _save:   { credentials: [noAlta, crear, enfermera] }
      edit:    
        title: Editar Recien Nacido %%ap_paterno%% %%ap_materno%%
        display:
          Examen Físico del Recien Nacido: [ap_paterno, ap_materno, fecha_nacimiento, sexo, peso_nacimiento, talla, circunferencia_torax, numero_cuna, fecha_adminision, fecha_egreso]
          Al Nacer: [_apgar]
#          Apgar: [apgar]
      new:     
        title: Nuevo Recien Nacido
        display:
          Examen Físico del Recien Nacido: [ap_paterno, ap_materno, fecha_nacimiento, sexo, peso_nacimiento, talla, circunferencia_torax, numero_cuna, fecha_adminision, fecha_egreso]
          Adicionar Apgar: [apgar]