generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolicitudReposicionMaterial
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solicitud_reposicion_material
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  ~
      list:    
        title: Solicitudes de Reposicion de Material
        display: [unidad, encargado]
        object_actions:  
          _edit:        { credentials: [noHistory] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [siHistory] }
          _delete:      { credentials: [noHistory] }
        actions: {}
        batch_actions: {}
      filter:  
        display: [unidad, encargado]
      form:    
        display:
          Datos Generales de la Solicitud de Reposición de Materiales: [unidad, encargado]
          Items Adicionados: [ _listado_items ]
          Adicionar Item: [ detalle ]
          #Detalle(s) de Material Registrados: [DetalleMaterial]
        actions:
          _list: ~
          _save: { credentials: [noHistory] }  
      edit:    
        title: Editar Solicitud de Reposicion de Material        
      new:        
        title: Nueva Solicitud de Reposicion de Material
        display:
          Datos Generales de la Solicitud de Reposición de Materiales: [unidad, encargado]
          Adicionar Item: [ detalle ]        