generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolicitudReposicionMaterial
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solicitud_reposicion_material
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  
        fecha:     {label: 'Fecha de Solicitud', date_format: 'dd/MM/yyyy'}
        unidad:    {label: 'Unidad solicitante'}
        encargado: {label: 'Encargado de la solicitud'}
        creator:   {label: 'Responsable'}
      list:    
        title: Solicitudes de Reposicion de Material
        display: [fecha, unidad, encargado, creator]
        object_actions:  
          _edit:        { credentials: [noHistory] }
          ver_detalle:  { label: Ver Detalle, action: edit, credentials: [siHistory] }
          _delete:      { credentials: [noHistory] }
        actions: {}
        batch_actions: {}
      filter:  
        display: [fecha, unidad, encargado]
      form:            
        actions:
          _list: ~
          _save: { credentials: [noHistory] }
      edit:    
        title: Editar Solicitud de Reposicion de Material        
        display:
          Datos Generales de la Solicitud de Reposición de Materiales: [unidad, encargado]
          Materiales Adicionados: [ _listado_items ]
      new:        
        title: Nueva Solicitud de Reposicion de Material
        display:
          Datos Generales de la Solicitud de Reposición de Materiales: [unidad, encargado]
          Adicionar Material:   [ _listado_items ]
